### ISSUE TITLE
05-UsingThePrivateDatastore

### ISSUE THREAD

**Issue by severinmenard** [hotosm/learnosm#105]
Hi,

Starting to translate it into French! On a Gdoc as a GITHub noob.

Noticed in this doc the contact to open a HOT Datastore account is Kate's private Gmail address. Maybe we could change this by accounts@hotosm.org now?

**Comment by Nick-Tallguy** [comment]
https://github.com/hotosm/learnosm/blob/gh-pages/_posts/fr/0400-12-25-private-data-storage-config.md  can only see this in the French language. Not sure if it's current.
If it is current, or someone xan update it (whichever language) it can go on Transifex in French for translation to other languages.
I'll have a look for the gdoc as well.

**Comment by Nick-Tallguy** [comment]
https://docs.google.com/document/d/1iLJK7kArj5OVmL-OBqWHFHBFE58MFVZ5sj46OmgAe74/edit

**Comment by Nick-Tallguy** [comment]
#124 refers. Needs updating. Closing as a duplicate
