### ISSUE TITLE
Export formats

### ISSUE THREAD

**Issue by sabas** [hotosm/learnosm#107]
In the old version of learnosm there was a pdf, what about making a section with ready to download exports?
I was thinking to pdf and also epub ( http://lincolnmullen.com/blog/epub-generator-for-jekyll/ )

**Comment by pyrog** [comment]
epub :+1: 

For pdf, a very quick search *"markdown pdf jekyll"* give:
* [plantheric/jekyll-plugins](https://github.com/plantheric/jekyll-plugins)
* [mre/karban](https://github.com/mre/karban)

But I suggested to tidy the code/structure of learnOSM before adding theses converters (See #306)

**Comment by pyrog** [comment]
I see this one [fauno/jekyll-pandoc-multiple-formats](https://github.com/fauno/jekyll-pandoc-multiple-formats).

It use [pandoc](http://johnmacfarlane.net/pandoc/) and produce **pdf**, **epub**…
To see it in action, look at [En Defensa del Software Libre](http://endefensadelsl.org) (an online/paper book build with **jekyll** and **pandoc**)

**Note:** direct conversion to pdf seem to produced *low quality* documents. See: [Generating publication-quality documents from the same website source](http://peterlu.github.io/2014/08/03/markdown_latex_pdf.html)

**Comment by bgirardot** [comment]
wow, very helpful @pyrog

**Comment by Nick-Tallguy** [comment]
Closing. I've been adding these as .odt's and .pdf's for some time. The exceptions are the HOT-tips section (mainly images), those modules waiting for review or those I've missed!
