### ISSUE TITLE
Re-organize topic groups (intermediate and advance) into coherent themes.

### ISSUE THREAD

**Issue by maning** [hotosm/learnosm#110]
From Mikel:

The division into "Beginner" and "Advanced" seems a little artificial. The "Beginner" section makes sense, but for more advanced topics, to me it makes more sense to group topically, and indicate level of difficulty as an attribute of each section. For instance 
- "More on Editing" (Editing in Detail, Presets, Private Data Store)
- Coordination (Tasking Server, Quality Control, Editing the Wiki)
- Sharing and Map Production (TileMill, github, maps on a website, WMS)
- Sys Admin (postgres set up, virtural machine set up)

Reference: http://lists.openstreetmap.org/pipermail/hot/2013-July/003370.html

**Comment by Nick-Tallguy** [comment]
Closing as stale. I've added the hot-tips section with guides for new iD users.im open to discussion on a different layout or pull requests.
