### ISSUE TITLE
Update screenshots

### ISSUE THREAD

**Issue by sabas** [hotosm/learnosm#115]
Example http://learnosm.org/images/start_osm_website_en.png

**Comment by harry-wood** [comment]
There's one screenshot on the very first page of the docs which still needs updating http://learnosm.org/en/beginner/introduction/    the photo on there is also visibly out of date in the same way, but that matters less.  (I see the next page about openstreetmap.org has more up-to-date screenshots)

**Comment by Nick-Tallguy** [comment]
Have gone for an image in Epworth, Harare - the previous one I chose was just a bit too generic & similar to one in the following guide. 
Closing issue now, but please reopen if there is an image you prefer
