### ISSUE TITLE
Updating Contributing.md to integrate prose.io for non techy translaters

### ISSUE THREAD

**Issue by severinmenard** [hotosm/learnosm#125]
We need an updated Contributing.md page explaining clearly what would be done for the translation process with prose.io, encompassing the following points:
- do I need to create my own branch or not? If so, the concept should be explained in simple words. 
- what is the expected URL root in which I am supposed to work?
- how do I upload the images?
- how can I visualize the resulting text with the inserted images?

**Comment by Nick-Tallguy** [comment]
Closing as all issues dealt with. See also #526
