### ISSUE TITLE
New Material and New Translations

### ISSUE THREAD

**Issue by jeffhaack** [hotosm/learnosm#138]
I'd like to document the recent changes I've made to learnOSM content and list a few things that are still needed:

First, what I've changed:
- In the Beginner Guide, there is now an additional chapter named "More about JOSM."  This chapter includes some of the original material from the "Editing in JOSM" chapter and some new material.  I thought it was important to give some grounding in JOSM editing before going into Field Papers and GPS.  The "Editing in JOSM" chapter remains, but is now covering just some more advanced JOSM stuff.
- I've done some general content edits to all of the Beginner Guide chapters - nothing very major, but updates to account for changes, new images where necessary.
- The images are now restructured a little bit as discussed elsewhere.  Images are in images/en/beginner/... and divided by folder.  There is still some discussion on this but for sure each language will have its own images folder.  I've made all images in the markdown documents into links at the end, rather than inline.
- I've reworked the intermediate and advanced chapters into new sections.  The completed sections are a new "Editing" section which has a lot more JOSM tutorials and one on iD, and "Map Design & Sharing," which has the mapbox and tilemill chapters.  There are folders for other sections too, but the chapters are marked as drafts because they need to be revised still.

So what's next?:
- First, we should shout out to interested translators about the new material.  The Beginner Guide translations should be updated (especially switching to Field Papers), and the new guides can use translation too.
- I think we should add the English versions into each language on the site where there are no translations, along with a local language message that says, "This chapter has not been translated into [the language]. Here it is in English.  If you'd like to help translate, go here..."
- There are still some chapters which need to be revised.  They are in the English folder and the filenames are preceded with "draft."  I'm not sure I have time to work on them right now, so if someone wants to polish them up we can add them to the site as well.

**Comment by pyrog** [comment]
> ideas on how we could quickly add the English version to areas that aren't translated

We could use layouts :wink:
See #252 and #306

**Comment by Nick-Tallguy** [comment]
Closing this now as I think all matters are resolved.
