### ISSUE TITLE
sticky nav does no longer fit on smaller screens

### ISSUE THREAD

**Issue by nebulon42** [hotosm/learnosm#139]
Now that the navigation box has more items and there is another box the nav does no longer fit onto smaller screens (e.g. my 1280x800 display). Maybe the stickyness should be removed altogether? As it is now I would have to scroll to the end to see the rest of the nav items. Instead of the sticky nav there could be also a sticky "to top of page" link.

**Comment by Nick-Tallguy** [comment]
Closing this now.

We have a return to top button.

We also have need of a new layout with cascading menus. 

Closing pending a pull request - please!
