### ISSUE TITLE
Teaching Content Format

### ISSUE THREAD

**Issue by MappingKat** [hotosm/learnosm#14]
Any thoughts on how we would like to organize the teaching guides? 

In all of the sections, there will be:

> - A general guide and agenda
> - Activities
> - Handouts (related to activities but more informative and less interactive... like the [Mapping Process](https://docs.google.com/a/hotosm.org/document/d/1bq4mK2vexwGSUwV0pFbRuR8KGuuMWObE93rotJdrSuA/edit) in Beginning guide) 
> - Quizzes (would love to hear opinions on the format of the quizzes... I was thinking of converting them all into Multiple Choice so that we can include answers at the bottom; however, some of the open ended questions are useful... Check [Beginning Quiz](https://docs.google.com/a/hotosm.org/document/d/1kx5gw1Yii3YRQ7J3xuitDsko1w6sen9xN7mhLIOLCtY/edit) and [Intermediate Quiz](https://docs.google.com/document/d/1NUMLR6t_k_ZKXLWxrvc3YiBH7Eqc96MHA7o5V3Piq68/edit)
> - Slides
> - Intermediate has some .osm samples and Advanced will have some additional guides

**Comment by Nick-Tallguy** [comment]
Closing as stale. No action in years
