### ISSUE TITLE
Adding Etrex10-20-30 chapter

### ISSUE THREAD

**Issue by severinmenard** [hotosm/learnosm#140]
Such a chapter has been done by Augustin Doury Last year. See https://docs.google.com/file/d/0B75-nI93RBqoOG81a3h4UWY0MzQ/edit?usp=drive_web 
Would be valuable to refresh the current chapter that I think relies on the older Etrex Hcx Series.

**Comment by Nick-Tallguy** [comment]
I'm closing this now as stale. If someone does it, that's great. But there are many devices and we can't cope with guides for all of them.

Contributions welcome
