### ISSUE TITLE
Better Sync'ing of Translations on Updates

### ISSUE THREAD

**Issue by wonderchook** [hotosm/learnosm#148]
The workflow defined now for new translations works okay. When we add new chapters that works as well. There isn't a good workflow for when the documentation is updated. 

Other documentation projects HOT is involved in use Transifex to track the changes and make it easier to contribute translations when strings change. I looked into what we might need to do if we were to use Transifex.

**Questions:**

Other applications HOT is involved in documentation for use PO files, is there a path to switch to this or should we be doing something else? 

Other possible file formats: http://support.transifex.com/customer/portal/articles/971979-supported-file-formats
Workflow InaSAFE is using as reference using QTLinguist (has been since moved to Transifex): https://github.com/aifdr/inasafe-doc

Any suggestions on a workflow for this? Or is there another tool we should be using? My major concern is now that we are updating LearnOSM that the translations are getting away from us.

@lxbarth @jeffhaack @mikelmaron

**Comment by Nick-Tallguy** [comment]
Using Transifex has mitigated this.  Update the source version and as the translations are done it removes the old versions.
