### ISSUE TITLE
Content formatting

### ISSUE THREAD

**Issue by lxbarth** [hotosm/learnosm#15]
@MappingKat on  #1:

> Yea, sorry about the format content.  Jeff and I should have clarified that
> earlier.  I think we were too overwhelmed with all of the information...  I
> think that for steps or directions in the guide we should have numbers.
> Bullets should be used for descriptors.  It's difficult because in some
> cases we bullet points and in others we write paragraphs.
> 
> This issue is also true with the slideshows.

**Comment by Nick-Tallguy** [comment]
Closing. There is a style guide and this issue is now stale.
