### ISSUE TITLE
Design Updates

### ISSUE THREAD

**Issue by jeffhaack** [hotosm/learnosm#170]
@jueyang @lxbarth 

I'd really like to do a couple of small tweaks to the interface, but I'm afraid that my absence of design sensibility will end up making a mess of it.  I wonder if you guys could help out, or at least give me some advice on how best to accomplish it.

What I think needs to happen is:
- on the homepage, "More Guides" needs to somehow point to the other guides we have added within the site, rather than to the wiki page listing Google Docs.  I don't know what the best way to do this is however, since there isn't really a single page for other sections.  My best idea would be to replace "More Guides" with links to each of the new guides, something like:
  ![screen shot 2014-01-23 at 5 13 50 pm copy](https://f.cloud.github.com/assets/322468/1989237/2e547034-8474-11e3-9a65-5bc7af8ef1a3.png)
- and I think we can remove the link to trainer material, as that doesn't currently point anywhere of use
- lastly, I added links to the other guides on sidebar - not sure if there is a better way to do this, but open to ideas
  ![screen shot 2014-01-23 at 5 21 18 pm](https://f.cloud.github.com/assets/322468/1989260/71d0c452-8474-11e3-9ddf-c7a412e77572.png)

**Comment by Nick-Tallguy** [comment]
Closing this now. We have a long term aim for a different layout.
