### ISSUE TITLE
Unify informations/tuts for newbies

### ISSUE THREAD

**Issue by Matthias84** [hotosm/learnosm#180]
Currently OSM has a lot of material (some outdated) that make it pretty hard for beginners to find the helping hand to get started with contributing
- http://wiki.openstreetmap.org/wiki/Video_tutorials
- http://wiki.openstreetmap.org/wiki/Beginners_Guide
- http://openstreetmap.de/123.html

This becomes to more clutter if we want to offer localisation and easy to read / focused tuts for different peergroups (non computer users, power users, ciris mapping, ...)

So how to combine this approaches under one roof?

**Comment by Nick-Tallguy** [comment]
@Matthias84 & @harry-wood I'd like to close this issue now - I don't think we've reached the goal yet, but I don't think having this issue as open will help either. I've just implemented some changes to make the beginner section simpler, but there is a long way to go still.

Just trying to tidy things up!
