### ISSUE TITLE
markup mess appearing at the bottom of "all chapters" page

### ISSUE THREAD

**Issue by harry-wood** [hotosm/learnosm#190]
In the "All chapters" section here: http://learnosm.org/en/beginner/all-chapters/

At the very bottom of the page after "Happy Mapping!" there's a bit of unrendered markup mess

**Comment by Nick-Tallguy** [comment]
I've removed 'all chapters' from the site at the moment. I'll shortly be producing .odf & .pdf files of the new beginners section, and a combined file, so they can be downloaded. 

If the 'all chapters' was needed for some other purpose, let me know.

**Comment by Nick-Tallguy** [comment]
Closing this - has not been a problem since removed in July 2015
