### ISSUE TITLE
Some images missing in German version

### ISSUE THREAD

**Issue by daganzdaanda** [hotosm/learnosm#204]
Hi, 
LearnOSM looks like a great help for newbies, thanks for putting this together! 
I quickly flipped through the German version and there are some dead img links:

​http://learnosm.org/de/beginner/introduction/

```
<img src="/images/intro_village_en.png" alt="A village in Indonesia" />
<img src="/images/intro_drawing_en.png" alt="Example of a hand-drawn map" />
```

http://learnosm.org/de/beginner/using-gps/

```
<img src="/images/gps_garmin_etrex_en.png" alt="Garmin eTrex Vista HCx"/>
<img src="/images/gps_aquiring_satellites_en.png" alt="GPS Positionsbestimmung"/>
<img src=​"/​images/​gps_all_en.png" alt=​"GPS alle">​
```

http://learnosm.org/de/beginner/walking-papers/

```
<img src=​"/​images/​paper_qrc_en.png" alt=​"paper QR code">
```

**Comment by michael63-osm** [comment]
cleaning up old issues which had been solved in the meantime
