### ISSUE TITLE
Spanish version shows Walking Papers instead of Field Paper

### ISSUE THREAD

**Issue by humitos** [hotosm/learnosm#232]
This guide seems to be outdated:
- http://learnosm.org/es/beginner/walking-papers/

and was replaced by:
- http://learnosm.org/en/beginner/field-papers/

I could work on the translation. Is it correct to update that guide to Field Papers? The OSM Wiki says that Field Papers is new and it should be used instead of Walking Papers.

**Comment by bgirardot** [comment]
This feels pretty important to me. I'd like to get something mentioned on the Spanish translation page that says something about Field Papers being the preferred site to use, but not available in Spanish. Less than ideal, but potentially saves someone wasting time if Walking Papers is not maintained any longer.

**Comment by humitos** [comment]
I'm working on this right now, I will push the changes and comment on this issue when I finished. Thanks!

**Comment by Nick-Tallguy** [comment]
@humitos I've just moved the field papers section for all languages to mobile-mapping where the chapter heading appears as 'Mapping with a Smartphone, GPS or paper'.

Following updates to the Fieldpapers website, we now have a current version of a guide in German & English. Would you be interested in translating to Spanish?

There is a 'staging site' at https://github.com/Nick-Tallguy/Nick-Tallguy.github.io which can make translation easier, as I can give you collaborator access, you work on the translation there, viewing the changes as you implement them, and when the translation is ready I pass it through to the main LearnOSM site.

Regards

Nick

**Comment by michael63-osm** [comment]
cleaning up old issues which had been solved in the meantime

The Spanish version of learnOSM contains a guide on field papers, though this refers to an older version of the interface
