### ISSUE TITLE
Update 404.HTML re translation

### ISSUE THREAD

**Issue by Nick-Tallguy** [hotosm/learnosm#252]
404.HTML appears to be the file displayed for broken link. Try out updating this so points also to Contributing.MD or other info about translating.
Test thoroughly - test branch?

As an example, go to http://learnosm.org/en/coordination/remote/
& then click on Deutsch at the top, and you will get this link
http://learnosm.org/de/coordination/remote/ - which at the moment just displays 
![selection_030](https://cloud.githubusercontent.com/assets/6763965/5427013/064fdca4-8379-11e4-8d27-1030c5e07f07.png)
Having displayed this, you have to go back to the learnosm home page & search again - you can't just chose a different language for some reason.

I think this image will be displayed every time a section is selected which does not exist yet.

Could the file 404.HTML be expanded so that it gives some information such as
"You have clicked on a link for a page that does not exist at the moment. In all probability this does exist in other languages - to see the content please try navigating to the section using an alternative language, such as English. 
If you are able, it would be very helpful if you could assist in the translation of this site - please click on the 
![selection_031](https://cloud.githubusercontent.com/assets/6763965/5427030/dedad592-8379-11e4-87c1-1658b75c074b.png)
icon for instructions on how you could help."

My suggested wording would need amending, and would be best if it appeared in a number of languages.

**Comment by pyrog** [comment]
See #306

**Comment by Nick-Tallguy** [comment]
I've created a custom 404.md file and deleted the 404.html file (new one is generated when the site builds using 404.md in the root folder) - the new file has links to the home pages in each language and a brief apology. Will apply fix shortly.
