### ISSUE TITLE
nl folder contains 3 files incomplete

### ISSUE THREAD

**Issue by Nick-Tallguy** [hotosm/learnosm#253]
Need to check each of 3 files & update as needed:
https://github.com/hotosm/learnosm/blob/gh-pages/_posts/nl/0200-12-30-BeginnenmetOSM.md  
https://github.com/hotosm/learnosm/blob/gh-pages/_posts/nl/0200-12-31-IntroductieinOpenStreetMap.md  
https://github.com/hotosm/learnosm/blob/gh-pages/_posts/nl/0200-12-29-GettingStartedWithJOSM.md

The pull request on these reads ' add 3 chapters in dutch (not live since the content is not completely…

… translated); minor change in language for front and beginner intr

This is from February 2013

It would be good for these to be assessed & perhaps the nederlands section of the site could then go live. Seems a pity they have sat here unused all this time

**Comment by michael63-osm** [comment]
cleaning up old issues which had been solved in the meantime

the Dutch part of the website is active
