### ISSUE TITLE
Fixing up the Contribute.md file

### ISSUE THREAD

**Issue by bgirardot** [hotosm/learnosm#259]
Edit: I mean the CONTRIBUTING.md file.

I think I see how I can make the contribution page a little more clear. I am in the process of editing it up and will issue a pull request for my changes when I am done.

https://github.com/hotosm/learnosm/blob/gh-pages/CONTRIBUTING.md

If anyone else is working on this file, please let me know here. I should have my version of this file done in about a day.

Regards,
Blake

**Comment by Nick-Tallguy** [comment]
see #526 and #329 - closing this issue now as contributing.md was updated and tidying is now being covered on the other issues
