### ISSUE TITLE
IDEA: Staging Site for LearnOSM

### ISSUE THREAD

**Issue by wonderchook** [hotosm/learnosm#262]
With the desire to make changes such as:
-translation workflow
-design of the site
-structure

It might be a good idea to set-up a staging site. What is everyone's thoughts?

**Comment by jeffhaack** [comment]
I think we can close it for now..

**Comment by wonderchook** [comment]
Actually we had an idea on how to make it easy. I think if we do major
changes it would be good to have an experimental site.

**Comment by Nick-Tallguy** [comment]
Okay, no problem

**Comment by jmarlena** [comment]
I have been working on two possible solutions, one is by reconfiguring the github repository with a submodule (details here: ) and another is by using Travis CI (described with the usecase of staging a Jekyll site here ). Any one familiar with these options? I am thinking Travis CI would be easier at this point but I still have a couple of things to work out for it.

**Comment by pyrog** [comment]
> It might be a good idea to set-up a staging site

+1 see also #306 


>  have been working on two possible solutions, one is by reconfiguring the github repository with a submodule (details here: ) 

Here, where ? :laughing: 

Do you need to build pages automatically with github?
It could possible to build them locally and then copying them to http://hotosm.github.io/learnosm/sandbox/

just set ```baseurl: /sandbox``` in the local _config.yml

It's also possible to create a fork in another hotosm project [learnosm-sandbox]() or in one of our personal github account.
Or even put many "Jekyll sites" in learnosm account:

```
http://hotosm.github.io/learnosm
  |
  +--production (baseurl: /production)
  |
  +-- sandbox
         |
         +-- test-pdf (baseurl: /sandbox/test-pdf)
         |
         +-- test-something-else (baseurl: /sandbox/test-something-else)
```

**Comment by jmarlena** [comment]
Oops, details for adding a submodule are from this blog . . . http://indelible.io/blog/2013/07/26/jekyll-deploy-script.html

**Comment by pyrog** [comment]
This is the same idea (replace ```sandbox/test-pdf``` by ```dev```), but it's very easy to develop and deploy.
Thank you **very** much :smile:

I'll will test this this morning

**Comment by pyrog** [comment]
> It's also possible to create a fork in another hotosm project learnosm-sandbox or in one of our personal github account.

This is the easiest way. (I've got a headache with submodules :hear_no_evil: )

If you create [learnosm-dev]():
* the path will be http://hotosm.github.io/learnosm-dev
* in _config.yml set baseurl to your project name:    
```yml
baseurl: learnosm-dev
```

**Comment by pyrog** [comment]
@jmarlena 
> another is by using Travis CI

The full process seem to be described in details here: [jekyll-travis](https://github.com/mfenner/jekyll-travis)

Note that they want to produce books, use panic to generate epub, pdf…, use different flavors of Markdown (like [Scholarly Markdown](http://blog.martinfenner.org/2013/06/17/what-is-scholarly-markdown/) that permit citations)

**Comment by pyrog** [comment]
Move the discussion about Travis to #328

**Comment by Nick-Tallguy** [comment]
Try out of a staging site at http://nick-tallguy.github.io/

currently displaying how the changes from #403 would look.

I currently have this (early stages though) as my working directory from which I will make changes to the main site - will have to see how it works out, but it should be convenient to try things out.

**Comment by Nick-Tallguy** [comment]
I've been using the site at http://nick-tallguy.github.io/ for some detailed updates and have found it extremely useful. I probably haven't set it up perfectly, but I am able to keep the sites in sync as needed. 

I'd like to close this issue now, if everyone is happy about the use of http://nick-tallguy.github.io/ as a shared resource staging site. If anyone would like collaborator access to it, just ask. I'd rather it was thought of as a shared resource to improve LearnOSM.

I still see this as an interim setup - I've been working at removing duplicate and redundant images to an eventual aim of having the site not managed as 'blog'.

**Comment by michael63-osm** [comment]
cleaning up old issues which had been solved in the meantime

everyone seems to be happy with it
