### ISSUE TITLE
http://learnosm.org/files/ => 404

### ISSUE THREAD

**Issue by althio** [hotosm/learnosm#263]
- follows https://github.com/hotosm/learnosm/issues/71#issuecomment-17603463 and https://github.com/hotosm/learnosm/commit/6c7efe3eac497a125fe3e4626242846adb2b0c85
- follows feedback by a French user.

issue not resolved on French version

**Comment by Nick-Tallguy** [comment]
This has been fixed - presumably by althio with the patch #267
