### ISSUE TITLE
contents/bookmarks for current page in sidebox

### ISSUE THREAD

**Issue by althio** [hotosm/learnosm#266]
Header or titles (as defined with Markdown) could be processed so that a 'table of contents' for the current page is displayed in the sidebox or at the top.

For instance with the current state of page http://learnosm.org/en/beginner/start-osm/
You would have the following entries as links:
- Getting started on OpenStreetMap.org
- > Visit the OpenStreetMap Website
- > Navigate the Map
- > View Different Map Styles
- > Create an OpenStreetMap Account
- > Adding Your First Points
- > Summary
- > Moving Forward

in the sidebox along the links for other pages and other guides.
It would give a quick overview of the page and easy access to specific parts of long pages.

![sidebar](https://cloud.githubusercontent.com/assets/9863567/5436835/19b46b3c-846b-11e4-80e4-58410dc1324f.png)

**Comment by pyrog** [comment]
> a 'table of contents' for the current page is displayed in the sidebox or at the top.

Like this:
[![jekyll - toc](https://cloud.githubusercontent.com/assets/2158081/5817812/f8f280f8-a0af-11e4-85da-9c14d29cc062.png)](http://jekyllrb.com/docs/quickstart/)

> Personally I don't like the sidebox - when I view the site on my laptop.

I saw a website where the TOC is on a sidebar, but this bar disappear automatically and reappear when you move the mouse pointer over it.

**Comment by Nick-Tallguy** [comment]
I like the idea of a TOC on a sidebar that disappears, and automagically reappears when you move the mouse pointer over it.

**Comment by pyrog** [comment]
I find an example : http://mbell697.github.io/2014/02/04/yeoman-angular-rails-html5mode/
Scroll down the page, and the sidebar disappear :smile: 

The source code is there: https://github.com/mbell697/mbell697.github.com/blob/master/js/app.js
It use a javascript/jQuery technic.

A similar sidebar animate only by CSS: http://codepen.io/chriscoyier/pen/umEgv

**Comment by Nick-Tallguy** [comment]
@pyrog thanks for that:  

1.  Example 1 only worked for me for a short while on my laptop, then stopped playing. It refused to do anything at all on my phone.
2.  Example 2 with the css panel (http://codepen.io/chriscoyier/pen/umEgv) worked extremely well & I thought was extremely good - both on my laptop & phone.

Would you be able to fork the LearnOSM site & produce a working version using the css panel method so we could check it out before making a decision. Likely to be a slow process as a number of people would want to look at it and test it out before it would gain approval & potentially get merged. 

Points that may need consideration;  

1.  How would it display in an area with poor bandwidth, such as Africa - would it improve or have a detrimental effect. (Personally I don't think it would make it worse, and has the potential to be better as there is less to be rendered each time, but I think we ought to check).  

2.  Is there a limit to the length of the side menu when it is exposed - scrollable?   

3.  Does it have any effect on the production of pdf's (Unlikely I would have thought & at the moment we haven't resolved that matter to our satisfaction either.).

Thanks again

Nick

**Comment by althio** [comment]
Second example (cssPanelMenu) is more convincing as it actually gives the
space to the main content when the sidebar folds.

On my device, the first example (yeoman -- java) has limited usefulness.
The sidebar is nicely hidden but the main content does not use the free
space.

**Comment by pyrog** [comment]
@Nick-Tallguy and @althio 
I was a quick search to discuss want you want. There are hundred of examples on internet :wink: 

> Example 1 […] refused to do anything at all on my phone.

Probably because your browser don't support javascript or javascript is disabled on your phone.


> Would you be able to fork the LearnOSM site & produce a working version.

Yes, but I don't want to do it now. I prefer to continue cleaning the structure of learnosm.

> 1• How would it display in an area with poor bandwidth ?

No effect, it just a very small css file.

> 2• Is there a limit to the length of the side menu when it is exposed - scrollable?

No

> 3• Does it have any effect on the production of pdf's

No, we have a stylesheet for screen, another for each media (print…). I think that pdf don't use CSS stylesheet at all :wink: 

> the main content does not use the free space.

I was a quick search. The CSS could be fine-tune to do what you want.

This discussion show that it's very important to separate graphic design (css, layout), content (.md files) and code (See #306)

**Comment by althio** [comment]
I do agree @pyrog sorry if I was too short and unclear.

graphic design:
Collapsible/hidden panel is an excellent idea and I support it. It is mostly intended to give additional space for the content. One thing I am not sure and would like to discuss here: automatic behavior or controlled by user?

(Example#1 is good for demonstrating the effect but fails at the main objective in my mind. Because the reclaimed space is left blank. Of course thousands of examples do it better, no need to convince me, I reassure you!)

code:
From my limited technical knowledge, basic understanding of web technologies and input from @pyrog I would say CSS is preferable over Java. But that is under the hood and any technology could certainly achieve similar effects. Acronym-ally speaking: AFIAK CSS is more KISS.

**Comment by althio** [comment]
The discussion derailed a bit towards the sidebar behaviour.
This is also related to #139.

I still consider this issue to be primarily focused on contents/TOC for the current page - if you don't mind. :)

**Comment by pyrog** [comment]
Sorry for digression, but we have a real example of moving side bar in learnosm:
![moving side bar](https://cloud.githubusercontent.com/assets/2158081/5969569/cdc970da-a825-11e4-88fc-ce8c4afe7de0.png)

**Comment by Nick-Tallguy** [comment]
@pyrog @althio not sure what is happening here, but when I visit http://learnosm.org/en/ the 'help improve our guides' sidebar does not move, but

when I run the site locally using http://localhost:4000/en/ & jekyll serve in a terminal, the sidebar moves.   

The whole site formats slightly differently depending on whether I run it locally or vist the website.

Think I need to have another try later in the day!

**Comment by pyrog** [comment]
> when I visit http://learnosm.org/en/ the 'help improve our guides' sidebar does not move

It works on my Mac with Chrome, Firefox and Safari.
May be it's a security settings that disable javascript for untrusted/remotes websites ?

Same thing for you with http://pyrog.github.io/learnosm-sandbox/en/beginner/ ?

> The whole site formats slightly differently depending on whether I run it locally or vist the website.

Probably because jekyll don't use the same markdown processor, or the version of Jekyll is different ?

You choose the converter by setting the ```markdown:``` variable in _config.yml (see http://jekyllrb.com/docs/configuration/#default-configuration)

Another reason is that github pages disabled some settings in _config.yml

**Comment by Nick-Tallguy** [comment]
Closing this now. Long term aim is to keep improving. For the moment I'm adding a table of contents as I review modules.
I'm also investigating other layouts with collapsing menus.
