### ISSUE TITLE
PDF version of LearnOSM

### ISSUE THREAD

**Issue by althio** [hotosm/learnosm#269]
[User feedback from mailto:learnosm@hotosm.org](https://groups.google.com/a/hotosm.org/forum/#!starred/learnosm/F15YkYZTqvI)

On http://wiki.openstreetmap.org/wiki/Beginners_Guide_1.6
There is a mention of a PDF file:
> Indonesia has inspired an amazing OSM Beginner's Guide (browse or download 37-page 42.3MB PDF @ LearnOSM.org, "Beginning OpenStreetMap: A Field Guide for Everyone")

But there is no link to get any PDF file.
We should put the same file again or remove the mention in the wiki.

Also would it be worthwhile to produce and propose PDF sections from learnOSM?

**Comment by bgirardot** [comment]
But we need to find out how they were created previously if there was an automated tool.

and we should find out if we can automate their generation from markdown as well as I think gdocs versions will slowly go away as they get converted to markdown.

As nick mentioned, previously they were generated from google docs, not markdown.

**Comment by pyrog** [comment]
Did you see this #107 :wink: 

It "easy" to produce automatically **pdf** and/or **epub** version with layouts and gems :smile:

**Comment by althio** [comment]
> Can we agree that the mention without any link or file on http://wiki.openstreetmap.org/wiki/Beginners_Guide_1.6 can be removed?

Done.


I am closing the issue.
We should sort the remaining issues on the subject (offline read, exports, PDF, ePub, ...) and choose the best option to continue discussion.
Possibly #107. See also #56. #1 is interesting for reference and we should keep some elements in mind but we will not re-open it! ;)
