### ISSUE TITLE
link or button to the next page or next section

### ISSUE THREAD

**Issue by althio** [hotosm/learnosm#270]
[User feedback from mailto:learnosm@hotosm.org](https://groups.google.com/a/hotosm.org/forum/#!starred/learnosm/c-opf8vU114)

As I understand this request:
We could add one (or more) link at the bottom of every page to continue the reading.
It could be a 'Next' button to the next page or next section.

Current state: some pages have links at the bottom but not all pages

**Comment by bgirardot** [comment]
@jmarlena 's additions look good to me.

**Comment by althio** [comment]
I agree the provided links are good.

Yet... :)
Do we keep the issue open, for links to be added in other guides (Detailed editing, Coordination...) or to make them programatically as suggested by https://github.com/hotosm/learnosm/issues/270#issuecomment-67222443 ...?

Clever links to other sections and other guides are a very nice touch for criss-cross reading but I must admit a simple link to the 'next page' still appeals to me. People unfamiliar with the subject may be more comfortable with linear reading as it ensures that nothing is missed.

**Comment by jmarlena** [comment]
Working on the next page button! I have the script for the next page but just trying to figure out where it goes.

**Comment by jmarlena** [comment]
Well after much trial and error I've added previous and next buttons that link to the other language versions of the post circled in red in the example below: 
![screen shot 2015-01-16 at 3 16 01 pm](https://cloud.githubusercontent.com/assets/6732600/5785971/cc880b70-9d92-11e4-9861-92a9e4a86446.png)

After playing with the file structure I checked out the Jekyll documentation and it basically says it's not possible to use the pagination "next" and "previous" for different categories!
![screen shot 2015-01-16 at 3 14 11 pm](https://cloud.githubusercontent.com/assets/6732600/5785986/ffb473a8-9d92-11e4-8695-059d9d276b10.png)
http://jekyllrb.com/docs/pagination/ 

However, I came across a blog post describing a plugin built for Jekyll to make a "category aware" next button so I will try exploring that as an option. 
http://stravid.com/en/category-aware-previous-and-next-for-jekyll-posts/

**Comment by Nick-Tallguy** [comment]
Closing this now - although we don't have a **next** or **previous** button, we now have a button at the bottom of each page that takes you back to the top, so you can easily access the menu to chose where you wish to go next.
