### ISSUE TITLE
out of sync posts in fr/beginner/

### ISSUE THREAD

**Issue by althio** [hotosm/learnosm#272]
learnosm/_posts/fr/beginner/0200-12-26-gps-1.md
is out of sync with the english version, with broken images and broken links.

**Comment by althio** [comment]
(new user feedback](https://groups.google.com/a/hotosm.org/forum/#!topic/learnosm/EFUblFLkggk)

related to outdated instructions and screenshots on
http://learnosm.org/fr/beginner/start-osm/#sauvegarder-une-image-de-la-carte

**Comment by Nick-Tallguy** [comment]
@althio I think this is now covered by #431 - if you are happy, can we close this one now?

**Comment by Nick-Tallguy** [comment]
Closing as sorted
