### ISSUE TITLE
Get iD web editor on the main left panel navigation

### ISSUE THREAD

**Issue by bgirardot** [hotosm/learnosm#276]
I feel that the navigation on the left hand side is not complete enough. For example there is no mention of iD web editor, the most used editor by new mappers.

Can we get something that links to the great tutorial on iD web editor?

**Comment by jmarlena** [comment]
I've been trying to find the right place to make this edit! I thought I could make changes in the _sites folder but that hasn't worked. Any ideas on where this change can be made? 

![screen shot 2015-01-02 at 4 30 25 pm](https://cloud.githubusercontent.com/assets/6732600/5600973/1307a084-929d-11e4-8b64-f669b3560bd4.png)

**Comment by bgirardot** [comment]
I do not know the answer to this but I was thinking the change would have to be made in the _layouts folder somewhere. But really I don't know, I thought that is where the automatically generated navigation is and we'd just have to stick a link to the id edtior section in there someplace.

**Comment by althio** [comment]
Solution 1:
Create a new page with the same structure as `0200-12-28-start-josm.md` but make it just a few explanations and link to said tutorial. I think browsing is cleaner this way because you can 'warn' that you provide a link outside the LearnOSM.
`0200-12-28-start-id.md`
```
---
layout: doc
title: Getting Started with iD
permalink: /en/beginner/start-id/
lang: en
category: beginner
published: true
---

Getting Started with iD
=============================

iD is blah-blah.
...
Please follow this link to online tutorial for editing with iD ...
...
```

Solution 2:
You can try to hack something. I think the generation of the navigation bar is in `learnosm/_layouts/doc.html` after L7 `{% for post in site.categories.[page.category] %}` but this is to be verified.
You might be able to make a link to iD tutorial to appear but you might also need to add a test to check that the current category is `beginner`. That is really a ugly hack but I could not think of something better if you start to mess with the automatically generated navigation. So Solution 1?

**Comment by jmarlena** [comment]
Hey Althio, 
I've been trying to figure out solution 2 with little success so I tried solution 1 with this pull request https://github.com/hotosm/learnosm/pull/295

**Comment by althio** [comment]
I do not have the ressources to test right away but it looks fine, very good page for introduction to iD.
It will be useful to add a mention to THE tutorial that is automatically launched with iD.

**Comment by jmarlena** [comment]
When you say THE tutorial you mean the automated walkthrough that is launched with iD?

**Comment by althio** [comment]
@jmarlena Yes.
@bgirardot Could you explain/confirm what you expect with "something that links to the great tutorial on iD web editor".

**Comment by bgirardot** [comment]
I just mean here in LearnOSM there is a very good iD tutorial. Let me find it.

**Comment by althio** [comment]
Damn that was not exactly what I had in mind... I think I misread your first post. Sorry for the confusion.

Let me explain what I recommended to jmarlena and tell me what you think (suitable or not, clear or not, useful or not, possible improvements).

Category beginner:
Add a short new page for iD
* introduction
* mention the walkthrough on iD site
* link to tutorial inside LearnOSM

Category editing (detailed)
Keep the existing section with tutorial.
Touch nothing.
(Maybe just make it to the top of the list above all the JOSM stuff.)

That way we end up with iD mentioned both in beginner's guide and detailed editing. But with two different pages and different contents.

**Comment by bgirardot** [comment]
That sounds good to me althio. Adding just the link into the nav sounds easier and quicker while the new page gets created :) but ya, your suggestion would be better for sure.

**Comment by althio** [comment]
@jmarlena Do we merge #295 as it is?
I think it is already a nice improvement.

We can leave here open to further discuss refinement and related ideas on the visibility of iD within LearnOSM.

**Comment by jmarlena** [comment]
I made a few minor changes to the id-editor file including: 
*changing the order of the iD editor page link so it should be above JOSM editing in the Navigation Bar 
*mentioning the walkthrough tutorial 
*improve visibility of the link to http://learnosm.org/en/editing/id-editor/

Here's the new commit. 
https://github.com/jmarlena/learnosm/commit/d2e7edf90c53f902aa9fe7d3dd8f4b1a4071b97e

Is this also a part of the #295 commit? (I don't have to do a new pull request, right?)

**Comment by althio** [comment]
@jmarlena Thank you i do think it is even better. I would like to receive other feedback but I would be happy to merge.
Though maybe we need another pull request or cleanup the commits.

**Comment by bgirardot** [comment]
@jmarlena I can't quite tell, but if you made the additional changes on the same branch on your local repository then the original pull request will have these additional changes. If you made them on a new branch you wound need a new pr for that branch. It looks to me like they are all on your issue#276 branch so the original pr should still be good for all the changes.

**Comment by Nick-Tallguy** [comment]
iD editor is now in prominent position in Beginner section #431 refers
