### ISSUE TITLE
Web Traffic Analytics?

### ISSUE THREAD

**Issue by bgirardot** [hotosm/learnosm#294]
Just curious if we want to put some sort of traffic analysis code on our pages so we can see where the traffic is going and how much we are talking about in general. I do not think we have access to the web server logs from github.

**Comment by althio** [comment]
This is maybe not essential but I agree it is a nice-to-have feature. I am
personally less interested in raw numbers and peaks after media coverage.
But it would be useful to check the most used and most needed sections, use
by language and other indicators for our internal use and prioritisation of
issues.

Additionally just having the numbers would be an incentive for ourselves to
try to increase audience. By improving quality, translations, as well as
visibility and publicity.

**Comment by bgirardot** [comment]
Yes, my feeling were along the same lines as althio's using some web traffic stats to help us prioritize translations or development of tutorial materials.

Maybe dodobas has some suggestions for tracking software. 

But a thumbnail sketch of how to do it is, if we do not have access to the raw web server logs, is to put a small piece of code on one of the template pages that makes a call to a web traffic stats provider like google analytics and that is about it. Then you visit the web traffic stats provider for traffic stats. 

Another one I liked the looks of was this one:
http://clicky.com/

Free for up to 3000 page views per day, which I think would cover learnosm, but I obviously don't know :)

But google analytics I think is free all the time, it is just you have be comfortable with google (which I am for the most part).

**Comment by jeffhaack** [comment]
Hi guys, we actually do have Google Analytics set up, which I think is
housed under my Google account.  I'm not sure if this is what you want, but
if you want to change it to a neutral account feel free to change the UA
code.

**Comment by bgirardot** [comment]
Here is the piwik code we can use for the learnosm site. This was discussed on the learnosm mailing list and I think we agreed to switch out from GA to piwik because it will be easier to make the piwik information public.

```
<!-- Piwik -->
<script type="text/javascript">
  var _paq = _paq || [];
  _paq.push(["trackPageView"]);
  _paq.push(["enableLinkTracking"]);

  (function() {
    var u=(("https:" == document.location.protocol) ? "https" : "http") + "://piwik.hotosm.org/";
    _paq.push(["setTrackerUrl", u+"piwik.php"]);
    _paq.push(["setSiteId", "3"]);
    var d=document, g=d.createElement("script"), s=d.getElementsByTagName("script")[0]; g.type="text/javascript";
    g.defer=true; g.async=true; g.src=u+"piwik.js"; s.parentNode.insertBefore(g,s);
  })();
</script>
<!-- End Piwik Code -->
```

Kate also suggested we remove the existing GA tracking code when we put this code in place.

dodobas tells me the piwik server is all set to go, we just need to put this code on the pages and it should start working.

piwik style stats can be seen here:
http://piwik.hotosm.org/

**Comment by Nick-Tallguy** [comment]
Blake,

I'm still on holiday so not in a position to help for a week or so, but
anything that gives an indication as to what it is worn spending time on is
good.

Could we also use this as a method of finding out what is needed most. Sort
of 'click here for a section on offset,
here for a section on River banks and Islands,
Here for buildings
Here for how to get a map into osmand,
Here for how to collect gps traces & upload them to osm,
Here for a free text message to the developers,'

Nick

Volunteer 'Tallguy' for
https://wiki.openstreetmap.org/wiki/Humanitarian_OSM_Team

http://www.openstreetmap.org/user/Tallguy

Treasurer, website & Bonus Ball admin for
http://www.6thswanleyscouts.org.uk/ (treasurer@6thswanleyscouts.org.uk)

**Comment by althio** [comment]
fixed by #323?

**Comment by bgirardot** [comment]
Lets just hold this open until the piwik stats are up and running, which as of right now I can not confirm. I mailed dodobas to ask about it but have not heard back yet. When I do I will close this one up if there are no objections.

**Comment by michael63-osm** [comment]
cleaning up old issues which had been solved in the meantime

stats are available, the links are in the Training WG meeting minutes
