### ISSUE TITLE
Add translation system

### ISSUE THREAD

**Issue by nutiteq** [hotosm/learnosm#3]
My suggestion: http://www.transifex.com, upload .po files there and have them translated by community. It has working CLI tools so you can have even automatic pull/push workflow of new strings and translations.

**Comment by jmarlena** [comment]
I found a really cool localization management tool called [Crowdin](https://crowdin.com/page/tour) that is free to open source projects. 

Here are some sample screenshots from a [Django Girls tutorial]( https://crowdin.com/project/django-girls-tutorial) kept on GitHub: 
![screen shot 2015-05-23 at 11 03 50 pm](https://cloud.githubusercontent.com/assets/6732600/7786905/49f51424-01a0-11e5-8653-017ea3b473a3.png)

![screen shot 2015-05-23 at 11 05 01 pm](https://cloud.githubusercontent.com/assets/6732600/7786907/4dc243f6-01a0-11e5-8178-61cba351499c.png)

We can try signing up for free at this link: 
https://crowdin.com/page/open-source-project-setup-request

This tool has the potential to drastically simplify the current translation workflow & encourage more translation help.  Any reason why we wouldn't want to test this tool to manage translations?

**Comment by jmarlena** [comment]
Potential Solution for issue [#13](https://github.com/hotosm/HOT-Project-Ideas/issues/13), #138

**Comment by jmarlena** [comment]
Update: It looks like POEditor offers direct GitHub Integration (Crowdin doesn't at this time) and the process looks easier than Transifex's integration process. 

PoEditor's GitHub Integration Setup/Process: 
https://poeditor.com/help/how_to_translate_a_language_file_from_a_github_project

Transifex's GitHub Integration Setup/Process: 
http://docs.transifex.com/integrations/github

I think POEditor looks like a good, easy-to-use & maintainable option.

**Comment by Nick-Tallguy** [comment]
Certainly we need to set in place a translation system. I don't know if @althio has had time to fully investigate Transiflex yet - I suspect not as he has been busy.

@jmarlena thanks for checking this out - could you prepare a workflow guide 'in rough' that we could compare with ? that althio may have, so we can work out which way to go. 

Thanks for investigating this so far. 

Nick

**Comment by Nick-Tallguy** [comment]
closing as we are using Transifex - working system, but am still open to suggestions as to making the system easier.
