### ISSUE TITLE
Marking out of date pages and parts

### ISSUE THREAD

**Issue by althio** [hotosm/learnosm#301]
It could be useful if we defined a standard procedure and easy steps to mark published content as "out of date".

That could be applied to:
- whole page
- part of a page
- all languages
- language by language

and we could use a combination among:
- github issue (by page? category? language?)
- github labels
- header on published site (note to self https://github.com/hotosm/learnosm/issues/252#issuecomment-67847450)
- mark by comments (only visible on source code)
- mark by note and/or special formatting applied to blocks (visible on published site)

It would be helpful to prioritise update and give notice to potential translators.

Anyone working on this? Any idea to formalise the workflow and steps?

**Comment by pyrog** [comment]
For content out of date, I suggest to use **front matter** and **layouts** to display a warning to the end users.
For part of pages, we could use **liquid tag** to mark the out of date section.

For missing pages, first we should **tidy learnOSM**, see #306.

After we coud use a bot that check every links in english pages to find translation in others languages (probably it could be only with layout and/or special pages)

**Comment by pyrog** [comment]
> github labels

+1 
I suggest also to add labels for content, design, code:
* content: add a chapter about GPS precision, editor xyz, remove obsolete part…
* design: add stylesheet for Dalton Visual impairment, new logo…
* code: bug with xyz feature…

**Comment by Nick-Tallguy** [comment]
Closing this now - we have been reviewing the modules for some time now, marking them with the date of the review, and updating them when they need it. It's not perfect, but it's mainly working. Can we open individual issues for any module we come across that needs updating and then update them whilst cross referring to the issue.
