### ISSUE TITLE
Call to Moving forward template is missing in all? pages (except english)

### ISSUE THREAD

**Issue by pyrog** [hotosm/learnosm#303]
**Moving forward** is missing at the bottom of each pages (at least for the **Beginner’s Guide**).

See #270

Also, for a lot of languages (Bahasa Indonesia, Português,  Italiano, français, Deutsch) **All chapters** is missing.

**Comment by Nick-Tallguy** [comment]
All chapters has been removed from all languages. Moving forward is present
