### ISSUE TITLE
Croatian translation continues with editing part

### ISSUE THREAD

**Issue by hbogner** [hotosm/learnosm#311]
Year ago we translated
http://learnosm.org/hr/beginner/

Now we forked learnosm and will soon start translating
http://learnosm.org/hr/editing/

Our fork is here:
https://github.com/osm-hr/learnosm/

**Comment by Nick-Tallguy** [comment]
@hbogner please make sure you update your repository / fork - I've just implemented some large movements of files. Nothing is deleted, but some topics are now in different folders. 

There is also a 'staging site' at https://github.com/Nick-Tallguy/Nick-Tallguy.github.io on which I test out changes before implementing them. I keep both up to date. I don't mind which one you work on, but if you are in any doubts you can always work on the staging site, on which I can give you collaborator rights. On the staging site you can them make your changes, view them, and when you are happy that they display correctly, let me know & I pass them on to the main site. 

I don't mind which method we use - I will keep everything in sync as needed.

Regards & thanks for your work on this.

Nick

**Comment by Nick-Tallguy** [comment]
Hi, not sure of the current state of play on this - may be easier for translations to continue on Transifex - certainly makes it easier for me to see what needs updating.

**Comment by hbogner** [comment]
Hi, translation stopped for now.
Since I have almost no time to do it, and others who volunteered to help didn't help with translation.
I'll make a note about the switch to Transifex, and delete out fork.
