### ISSUE TITLE
Improve search data file

### ISSUE THREAD

**Issue by pyrog** [hotosm/learnosm#315]
1. The files generated by jekyll contain a lot of spaces and empty lines, especially all-translation.json used by the jQuery search script.
   It could be minified with a Jekyll plugin or ruby script run by travis/rake.
2. Also, this file contain titles in all languages but the search script use only the current language.
   So, we could generate a file by language and load only one at a time.
3. Search take care of accentuated char:
   - In french the search `editeur` return _"Edition avancée"_, _"Editer le Wiki OSM"_
   - The search `éditeur` find _"Éditer à distance…"_, _"Éditeur iD"_, _"Éditer avec JOSM"_

:bulb: To "fix" this, I suggest to test a plugin with full text search capabilities like [jekyll-lunr-js-search](https://github.com/slashdotdash/jekyll-lunr-js-search)

**Comment by althio** [comment]
Originates from https://github.com/hotosm/learnosm/issues/19#issuecomment-13016637
Discussed in https://github.com/hotosm/learnosm/issues/150

Need to assess the proposal from @pyrog with
> :bulb: To "fix" this, I suggest to test a plugin with full text search capabilities like [jekyll-lunr-js-search](https://github.com/slashdotdash/jekyll-lunr-js-search)

**Comment by pyrog** [comment]
See #328 to discuss how to use Travis.CI

**Comment by Nick-Tallguy** [comment]
Closing as stale. A champion willing to work on this is weL come to open it and work on it.
