### ISSUE TITLE
Add style recommendations

### ISSUE THREAD

**Issue by althio** [hotosm/learnosm#324]
Add style recommendations for editors and translators.
Possibly in a readme/contribute/contributing page.
See existing proposal in this [Proposed Style Guide for LearnOSM](https://hackpad.com/Proposed-Style-Guide-for-LearnOSM-1JJxS8NIQSX).

started at https://github.com/hotosm/learnosm/issues/261#issuecomment-72178239

**Comment by althio** [comment]
related to https://github.com/hotosm/learnosm/issues/82
closing as duplicate?

**Comment by Nick-Tallguy** [comment]
I'm happy for you to close & we go with #82
