### ISSUE TITLE
Learnosm's "sample.osm" regularly turns up in OSM's live data.

### ISSUE THREAD

**Issue by SomeoneElseOSM** [hotosm/learnosm#335]
If you look here:

http://www.openstreetmap.org/#map=18/0.06799/0.06214

edit the area with Potlatch 1:

https://www.openstreetmap.org/edit?editor=potlatch#map=18/0.06799/0.06214

and select "undelete" you'll see lots of familar data - "Happy Park", "Cat Forest" etc.

Part of the problem may be that there's nothing on http://learnosm.org/en/beginner/start-josm/ that tells the user what to do with their test data and gets them editing live data.  JOSM will prompt that something needs uploading, and by definition learnosm folks won't have seen the prompt before, so it's only fair to talk them through discarding their test edits and editing "for real" for the first time.

**Comment by althio** [comment]
Thanks for the investigation and report. Sorry we did not catch your
request on OSM-talk last month.​

If anyone can propose a better structure or wording it will be most welcome.
Otherwise we will try to resolve with appropriate warning as soon as we can.

**Comment by maning** [comment]
We can also add `upload='false'` in the sample.osm https://github.com/hotosm/learnosm/blob/gh-pages/files/sample.osm#L2

So that JOSM users can be reminded not to upload.

**Comment by althio** [comment]
@maning Done, thanks. It provides a strong warning against upload.

http://learnosm.org/en/beginner/start-josm/
https://github.com/hotosm/learnosm/blob/gh-pages/_posts/en/beginner/0200-12-28-start-josm.md
may need some additional instructions to explain how to properly remove the sample.osm layer.

**Comment by SomeoneElseOSM** [comment]
For info, I've just deleted another example - http://www.openstreetmap.org/changeset/30425450 .

**Comment by SomeoneElseOSM** [comment]
I'm not sure the "string warning" is working - I've just deleted another "Cat Forest" et al in http://www.openstreetmap.org/changeset/31645498 (in among some other stuff).

**Comment by jaakkoh** [comment]
I created a ticket for this at https://josm.openstreetmap.de/ticket/12731

**Comment by planemad** [comment]
One more instance of garbage at null island http://osmcha-django-staging.tilestream.net/37558836/

**Comment by jaakkoh** [comment]
All of these cases are confirmations that an upload=never parameter would be much needed. I was running into this issue a number of times already with my tech team in Haiti that I tasked in 2012 to clean up license change damage all over the island of Hispanola (= Haiti + DR) & do some additional tracing of blank areas. Back then I had identified areas that needed more work and then created a an .osm file to which I had drawn these area. The boundary layer got uploaded quite a number of times even with the upload=false parameter. Upload=never would be also good for Tasking Manager tile bounds.

**Comment by SomeoneElseOSM** [comment]
Although it went quiet for a while, learnosm test data has been popping up again recently.  My latest "bucket and shovel" changeset was https://www.openstreetmap.org/changeset/43124451 .

**Comment by althio** [comment]
@SomeoneElseOSM
I am sorry, truly, that the test data still gets through and give you cleanup and discussion work.
However this particular user did add data in the same changeset, as you noticed https://www.openstreetmap.org/changeset/42939117.
I am not sure what we can do to prevent people to test data then start real mapping but without removing the test data.

upload=never parameter would be useful @jaakkoh

**Comment by Nakaner** [comment]
There is [another case](https://www.openstreetmap.org/changeset/46666195) where this data hit OSM. I reverted the whole changeset.

**Comment by althio** [comment]
http://learnosm.org/en/josm/start-josm/
https://github.com/hotosm/learnosm/blob/gh-pages/_posts/en/josm/1900-12-21-start-josm.md
This page does need some additional instructions to explain how to use and **discard** the sample.osm layer.

**Comment by bgirardot** [comment]
We could also add instructions for JOSM at least, how to mark the layer "Do not upload" I am not sure if that is something we can add to the OSM file itself or not.... I will check.

**Comment by bgirardot** [comment]
Yes, JOSM has a "Discourage Uploading" setting you can put on a layer, then when saving that layer, it will stay with the layer. 

So it should be trivial to modify this sample file to have the discourage upload flag.

In addition to maybe adding some text that makes it clear not to upload it.

**Comment by michael63-osm** [comment]
The "discourage uploading" setting is equivalent to the parameter "upload=false" attached to the file as suggested in the comments from 2015-03-10. I just verified that trying to upload the data from sample.osm results in a strong warning.

But, now the latest development in response to [Jaako's josm ticket](https://josm.openstreetmap.de/ticket/12731) from 2016-04-10: Today the josm developers implemented "upload=never"! Thank you Benoît - I assume updating that ticket triggered someone to implement this.

I just verified that this flag shows the same behaviour on my current josm version (the strong warning) so I modified sample.osm on learnOSM accordingly.

I am looking forward to updating josm to a more recent version soon and verify that we should get rid of this nasty problem.

**Comment by michael63-osm** [comment]
Just tested with latest nightly build (11714): hey, it works! Loading sample.osm leaves the upload button and menu entry inactive. Now we just have to add something to the introductory josm guide on how to get rid of that layer before making meaningful edits.

**Comment by michael63-osm** [comment]
I updated [the documentation](http://learnosm.org/en/josm/start-josm/) and put the new version on Transifex for translation

**Comment by Nick-Tallguy** [comment]
@michael63-osm - thanks for sorting this out!

**Comment by althio** [comment]
Good job from the JOSM team and @michael63-osm for the test, updated and augmented documentation here.

I think we are in good standing, even though the trouble can resurface with an older version of the sample data set and/or JOSM.

**Comment by SomeoneElseOSM** [comment]
The problem is still occurring.  See https://www.openstreetmap.org/changeset/57164343 for the latest example.  That's not an old version of JOSM - is there a way to tell if it's an old version of the test data?

**Comment by althio** [comment]
@SomeoneElseOSM 

You could ask the users to share their file sample.osm and check the upload=* parameter but I don't think you can find out only with the uploaded data.
The test data is the same since 2013.
Only the parameter was changed for upload=false since 2015 then upload=never since 2017.

**Comment by SomeoneElseOSM** [comment]
Thanks.  Previous requests to learnosm users have usually gone unanswered, because (a) they're obviously very new to OSM, and (b) often don't have a first language that I either write or can be confident of a good online translation in.  The current example is Chinese, which falls into the second category.

Would it perhaps be possible (perhaps for the next release) to modify the data slightly so that the version is accessible (perhaps as a "note" tag on a particular object, or in some other way)?

**Comment by maning** [comment]
Or we re-think this approach to onboarding people new to OSM.  I used this guide in previous workshops and its very effective but we have to remind people not to upload the sample data.  Its dangerous if people are using this on a self-paced approach.

**Comment by SomeoneElseOSM** [comment]
Another approach would be to mirror what iD does - have a guided tutorial with edits thrown away afterwards (or edits made to the dev site).  Anything that depends on "download this .osm from here" could potentially cause a problem in the future.  Obviously that's a lot more work and needs more than just documentation, though.

**Comment by michael63-osm** [comment]
The current version of the sample data cannot be uploaded through a JOSM version not older than one year. 

If people still upload these data then we have to assume that they got an older version of the data through a mirror or some other site providing them. That is something which we cannot prevent.

**Comment by althio** [comment]
> @maning 
Or we re-think this approach to onboarding people new to OSM. I used this guide in previous workshops and its very effective but we have to remind people not to upload the sample data. Its dangerous if people are using this on a self-paced approach.

When was the last time you faced this situation? This whole issue explains our attempts and progresses on this matter, and what you describe should be impossible with the current guide and test data.

**Comment by althio** [comment]
> @SomeoneElseOSM 
Would it perhaps be possible (perhaps for the next release) to modify the data slightly so that the version is accessible (perhaps as a "note" tag on a particular object, or in some other way)?

This guide can be modified anytime, there is not really "releases".

You can suggest exactly what would be better in the test data, and discuss that, maybe in a new issue?
And propose a new file in a pull request of course. :)

> Another approach would be to mirror what iD does - have a guided tutorial with edits thrown away afterwards (or edits made to the dev site). Anything that depends on "download this .osm from here" could potentially cause a problem in the future. Obviously that's a lot more work and needs more than just documentation, though.

And more importantly: this is for JOSM development, not for LearnOSM.

**Comment by SomeoneElseOSM** [comment]
Just for info, this has just happened again in https://www.openstreetmap.org/changeset/152433586 .  

I mention this just for info - clearly it's not a pressing issue to as whatever mitigation is in place has worked for 6 years with just one slipping through the net...

**Comment by michael63-osm** [comment]
Just as I said 6 years ago: remotely current versions of this file cannot be uploaded through JOSM. The layer info window says "upload is blocked". We cannot do anything about previous file versions floating through the universe.
