### ISSUE TITLE
HOT QuickStart Guide

### ISSUE THREAD

**Issue by jmarlena** [hotosm/learnosm#337]
There's a need to have one succinct HOT QuickStart Guide that links to other helpful guides and includes practical advice.

**Comment by jmarlena** [comment]
Here's a HOT QuickStartGuide I've been working on at Kate's request. Could use feedback on it including any additional input for the advice/encouragement and learning resources section. Also not sure where it should live on the site (if anywhere). 

https://gist.github.com/jmarlena/6af3852a66a87c2a155d

**Comment by jmarlena** [comment]
Here's a HOT QuickStartGuide I've been working on at @wonderchook's request. Could use feedback on it including any additional input for the advice/encouragement and learning resources section. Also not sure where it should live on the site (if anywhere). 

Put in the Beginners Chapter after JOSM editing. 
See PR#338. 
Also here as a gist: 
https://gist.github.com/jmarlena/6af3852a66a87c2a155d

**Comment by althio** [comment]
Compare also with ideas for a Quick start guide at #334.

**Comment by Nick-Tallguy** [comment]
Both guides are now in use.  #431 has moved glossary to beginner & HOT remote guide to coordiantion
