### ISSUE TITLE
Potlatch 2 - how to show the boundary square from Tasking Manager

### ISSUE THREAD

**Issue by Nick-Tallguy** [hotosm/learnosm#348]
Paste of my reply to an email on HOT mailing list following query - Wiki at http://wiki.openstreetmap.org/wiki/OSM_Tasking_Manager#Adding_the_grid_square_to_Potlatch also requires updating.  
1. Tasking Manager - obtain your square,  
2. Tasking Manager - select 'edit with JOSM' and under the words 'edit with josm' you will see a line of text 'Tip:Download the following gpx file .......'  
3. click on download file & make a note where you put it.  
4. Tasking Manager - using the dropdown list, change from JOSM to 'Potlatch 2' - this will open in a new tab,  
5. Potlatch 2, select Background / Vector File - use the menu to load the gpx file you downloaded.  
6. Make sure there is a tick in the 'show' column before you close the window down.  
7. Potlatch should now display the boundary as a square - blue in my case. Potlatch will still download data outside the area, so be careful about watching for the boundary.

**Comment by neuhausr** [comment]
Nick, I was thinking about adding this, but there's no Potlatch page in LearnOSM. I'm a GitHub newbie--what would it take to create one?

**Comment by althio** [comment]
@neuhausr 
A page about Potlatch may belong here:
https://github.com/hotosm/learnosm/tree/gh-pages/_posts/en/beginner
So one could create a new file with the + sign (like 0200-12-28-start-potlach.md?), with a copy/paste of another page as a starting point (0200-12-28-start-josm.md?)

However that bit of information is relevant in the context of the Tasking Manager, so maybe it does not need a new page. We could consider a few words about Potlach on http://learnosm.org/en/coordination/remote/ by editing in https://github.com/hotosm/learnosm/blob/gh-pages/_posts/en/coordination/0500-11-16-remote.md

Hope that make sense to you.

**Comment by Nick-Tallguy** [comment]
Issue created on Tasking Manager requesting the border square is loaded automatically.  https://github.com/hotosm/osm-tasking-manager2/issues/596

Until that permanent fix is obtained, I suggest we add a paragraph to https://github.com/hotosm/learnosm/blob/gh-pages/_posts/en/coordination/0500-10-23-tasking-manager.md explaining how to load the file from the JOSM option.

@neuhausr would you like to add the bit into the tasking manager section and add a pull request? If not, let me know & I will add it. Also, if you are interested in adding more info about Potlatch 2 into LearnOSM, but are having difficulties, please let me know & I'll do what I can to help.

Thanks.

**Comment by neuhausr** [comment]
Thanks for creating the TM issue for Potlatch. 

I just added the workaround to the learnosm TM page as suggested and created a pull request. I understood althio's explanation about how to create a new page, but just haven't had time to get to it!

One note on the TM page--is there a way to have an overview of the sections at the top of the page? (kind of like how wikis automatically include an outline of the page at the top) That page is so long, I would imagine a new user trying to navigate it might easily give up.

**Comment by Nick-Tallguy** [comment]
@althio I think @neuhausr has a very valid point there about a small index at the top of the Tasking Manager section - I'm thinking of something similar to the one I've created for the remote section. Not sure who else we need to check with, or if I get straight on with adding it. Nick

**Comment by althio** [comment]
Thank you @Nick-Tallguy for the issue hotosm/osm-tasking-manager2#596 we need to monitor it.
Thank you @neuhausr for the pull request #354, merged.

I don't close this issue yet because I want to discuss a bit more.
What is the best place to refer to the border square in any editor (iD, JOSM, Potlatch)?
http://learnosm.org/en/coordination/remote/
or
http://learnosm.org/en/coordination/tasking-manager/

Regarding the index: I agree it is a valid point.
One can provide a temporary fix (get straight on with adding it).
The permanent (automatically) fix would be like in issue #266.

**Comment by Nick-Tallguy** [comment]
@althio I think the update to http://learnosm.org/en/coordination/tasking-manager/ is sufficient at the moment. Although it may be nice to have more info on using Potlatch 2, I personally don't have the skills - about 5 years since I regularly used it, and I only see it now at mapathons when helping a newbie who can't use JOSM or iD. I seem to remember it's pretty intuitive. 

I agree about an auto index - for the future it would be really nice.In the meantime I'll try to work on a manual one soon.

**Comment by althio** [comment]
Most is done, so closing.
Please open as a new issue if a full page for Potlatch is to be considered (though it is not much used by new users compared to iD).
