### ISSUE TITLE
New translation into Norwegian?

### ISSUE THREAD

**Issue by andersar** [hotosm/learnosm#352]
Hi!
I'm not too familiar with working on Github, but I get some assistance from my better half.
I'm eager to get LearnOSM translated into Norwegian. Although most Norwegians learn English early in school, many (older) people do not have the skills nor the time to translate it while at the same time understand the content.

Could some admin set up so I can translate (preferably) most of LearnOSM ? :)

**Comment by althio** [comment]
Hi @andersar 

Thank you very much for your interest and your proposal for contribution!

We will set up as soon as possible the Norwegian language and initial pages.
In the meantime, please review the content at https://github.com/hotosm/learnosm/blob/gh-pages/CONTRIBUTING.md and please tell us if you have a preferred option for the translation workflow.

**Comment by andersar** [comment]
Excellent. I was thinking option B was the most efficient way for me to get going.

**Comment by Nick-Tallguy** [comment]
@andersar thanks for volunteering on this. Just to start us off, we need to add Norwegian to the index - can you translate the following please. I've included the English, Spanish & French, just to give an example for the Norwegian. I will then add that to the _config.yml file which I think will add Norwegian into the index at the top of the site pages.

en:
    tagline: "Learn OpenStreetMap Step by Step"
    contribute: "Help improve our guides"
    trainingspan: "Are you a workshop organizer?"
    training: "Check out training material for this guide (in English)"
    feedbackspan: "Was this chapter helpful?"
    feedback: "Let us know and help us improve the guides!"
    getstarted: "Get started"
  es:
    tagline: "Aprende OpenStreetMap Paso a Paso"
    contribute: "Ayuda a mejorar las guías"
    trainingspan: "¿Eres el organizador de un taller?"
    training: "Revisa nuestros materiales de aprendizaje para esta guía (en inglés)"
    feedbackspan: "¿Este capítulo te resultó útil?"
    feedback: "¡Contacta con nosotros y ayúdanos a mejorar estas guías!"
    getstarted: "Comencemos"
  fr:
    tagline: "Apprendre OpenStreetMap pas à pas"
    contribute: "Contribuer à ces guides"
    trainingspan: "Vous organisez des ateliers ?"
    training: "Consulter le matérial d'apprentissage (en anglais)"
    feedbackspan: "Avez-vous trouvé ce chapitre utile ?"
    feedback: "Aidez-nous à améliorer ces guides en donnant vos impressions!"
    getstarted: "Commencer"

Once you've done that, let me know which section you would like to start on and I'll add it across. 

Regards

Nick

**Comment by althio** [comment]
Tak @andersar & thanks @Nick-Tallguy 
Sorry for the delay.

In addition to this lines in `_config.yml`, you need to add the language in _layouts/default.html
```
+        <a lang='uk'>Українська</a> |
+        <a lang='no'>Norsk</a>
```

**Comment by andersar** [comment]
First attempt here, a few words are a bit lacking in direct (and good) translation into norwegian. Maybe due to the simple fact that the english language has a factor of 10 more words to choose from... :)

en:
tagline: "Learn OpenStreetMap Step by Step"
contribute: "Help improve our guides"
trainingspan: "Are you a workshop organizer?"
training: "Check out training material for this guide (in English)"
feedbackspan: "Was this chapter helpful?"
feedback: "Let us know and help us improve the guides!"
getstarted: "Get started"

no:
"Lær deg OpenStreetMap steg for steg"
"Hjelpe oss å forbedre våre guider"
"Kan du hjelpe til med å organisere workshops?"
"Se her for øvelser for denne guiden (på norsk)"
"Var dette kapittelet nyttig?"
"Gi oss tilbakemelding og hjelp oss med å forbedre guidene!"
"Kom i gang"

**Comment by althio** [comment]
Setup #356
Ready to start translation.

**Comment by Nick-Tallguy** [comment]
Hi @andersar there are 1 or 2 files in https://github.com/hotosm/learnosm/tree/gh-pages/_posts/no/beginner ready for translation. Let us know if there are any problems, or any way we can help. I think the images for these files are okay with the same as the English, but later on with other files we will have to produce some alternatives - easy way is for you to obtain the images you like, email them to one of us, and we upload them - but we can cross that bridge when we reach it. 

Good luck, and thank you.

**Comment by Nick-Tallguy** [comment]
@althio I've checked all of the files in the Norwegian and language settings, and everything is correct, but we still have an issue with Norsk displaying some of the time. It is recording this as 'http://learnosm.org/false/beginner' and I think the software is interpreting 'no' as 'false'. We may have to use a different two letter code! I've tried using speech marks & that didn't help. It's very strange because it doesn't do it for all of the files?

**Comment by andersar** [comment]
I've completed the 2 first files, and had them independently reviewd/spellchecked. Could you make another set of files available so I can get some work done on them during the weekend? :)

**Comment by Nick-Tallguy** [comment]
@andersar all looks very good. I've created a staging site, which may make things a little easier for you - if you go here https://github.com/Nick-Tallguy/Nick-Tallguy.github.io and click on the fork symbol 
![image](https://cloud.githubusercontent.com/assets/6763965/8022056/1b257166-0cb3-11e5-8bc4-92fd573bab59.png)

When you've done a little translating and you want to see what it will look like, just click on the 
![image](https://cloud.githubusercontent.com/assets/6763965/8022062/700ef92c-0cb3-11e5-8e95-3f1ff16a47a3.png) green button to make a pull request.

Try to keep your copy of the site up to date - 
![image](https://cloud.githubusercontent.com/assets/6763965/8022064/99236e74-0cb3-11e5-8f3d-7079b05c5e1e.png)

click on the words 'Pull Request' when you see a message about your fork being xxx number of commits behind XXXXX & that way you will have the latest version. 

Don't worry if this seems difficult - just send a message & we'll work it out. 

The staging site is at http://nick-tallguy.github.io/nb/beginner/introduction/

Any problems, get back to me

**Comment by Nick-Tallguy** [comment]
@andersar I've put the amended files onto the full site at http://learnosm.org/nb/beginner/introduction/ - looks very good to me.
When you're translating, could you also do '0100-01-01-contribute.md' & '0100-01-01-index.md' - anything which is in speech marks will need translating, such as   
 "OpenStreetMap is a free street level map of the world, created by an ever growing community of mappers."  

Don't worry about updating the wrong sections - my job is to make any corrections on the staging site so that it's sorted out by the time it gets to the main site.

Thanks for your work on this.

Nick

**Comment by andersar** [comment]
@Nick-Tallguy Completed. Although index.md seems empty when I open it in Prose?
Had independent review on all the text as well, think it is 98% sound and correct Norwegian now.

**Comment by Nick-Tallguy** [comment]
@andersar please make sure you update your repository / fork - I've just implemented some large movements of files. Nothing is deleted, but some topics are now in different folders. 

There is also a 'staging site' at https://github.com/Nick-Tallguy/Nick-Tallguy.github.io on which I test out changes before implementing them. I keep both up to date. I don't mind which one you work on, but if you are in any doubts you can always work on the staging site, on which I can give you collaborator rights. On the staging site you can them make your changes, view them, and when you are happy that they display correctly, let me know & I pass them on to the main site. 

I don't mind which method we use - I will keep everything in sync as needed.

Regards & thanks for your work on this.

Nick

**Comment by Nick-Tallguy** [comment]
This and other languages are now using the system on Transifex  - closing this. Open to discussion if another system becomes apparent.
