### ISSUE TITLE
tasking manager#edit with josm section unclear

### ISSUE THREAD

**Issue by harry-wood** [hotosm/learnosm#358]
Looking at ["tasking manager#edit with josm" section here](https://github.com/hotosm/learnosm/blob/gh-pages/_posts/en/coordination/0500-10-25-tasking-manager.md#edit-with-josm)

The sentence here is a bit long and complicated in general, but also what is the "download data automatically" plug-in?  I wondered if maybe it means the "continuos download" plugin?

**Comment by althio** [comment]
fixed in https://github.com/Nick-Tallguy/learnosm/commit/e361c13fe55c2be78c671f176a730c233fcc1511
https://github.com/hotosm/learnosm/pull/357
