### ISSUE TITLE
Translation into Kiswahili

### ISSUE THREAD

**Issue by kateregga1** [hotosm/learnosm#359]
Hello,
I am starting a translation of LearnOSM into Kiswahili. It is a lingua franca of the African Great Lakes region and other parts of Southeast Africa, including Tanzania, Kenya, Uganda, Rwanda, Burundi, Mozambique and the Democratic Republic of the Congo.

I'm a newbie to GitHub and I would appreciate any help on getting the translation on the site. 

Thanks.

**Comment by Nick-Tallguy** [comment]
Hi & welcome.

Thanks for offering to help with a translation. 

Please read through  https://github.com/hotosm/learnosm/blob/gh-pages/CONTRIBUTING.md and let us know your preferred option. 

I've started to add a section - have listed this as Swahili, purely because the software needs a two letter language code, and when I searched on Kiswahil I was redirected to http://en.wikipedia.org/wiki/Swahili_language. I apologize if I've got this wrong.

I've prepared two files  - Introduction and beginner, from the beginners section of the site, but if you prefer to start with another section, please let me know & I will make the preparations. 

One person always checks another persons work, so there will be a short delay until someone else, probably Althio, checks that I have not made any mistakes, and then the two files for translation will appear. 

Good luck, and please let me know if there is any problem.

Regards

Nick (Tallguy)

**Comment by Nick-Tallguy** [comment]
@kateregga1 

Sorry, forgot to add we will also need a translation for the following - I've included English, French and Spanish purely so you can see which actual bits need translation.

en:
tagline: "Learn OpenStreetMap Step by Step"
contribute: "Help improve our guides"
trainingspan: "Are you a workshop organizer?"
training: "Check out training material for this guide (in English)"
feedbackspan: "Was this chapter helpful?"
feedback: "Let us know and help us improve the guides!"
getstarted: "Get started"
es:
tagline: "Aprende OpenStreetMap Paso a Paso"
contribute: "Ayuda a mejorar las guías"
trainingspan: "¿Eres el organizador de un taller?"
training: "Revisa nuestros materiales de aprendizaje para esta guía (en inglés)"
feedbackspan: "¿Este capítulo te resultó útil?"
feedback: "¡Contacta con nosotros y ayúdanos a mejorar estas guías!"
getstarted: "Comencemos"
fr:
tagline: "Apprendre OpenStreetMap pas à pas"
contribute: "Contribuer à ces guides"
trainingspan: "Vous organisez des ateliers ?"
training: "Consulter le matérial d'apprentissage (en anglais)"
feedbackspan: "Avez-vous trouvé ce chapitre utile ?"
feedback: "Aidez-nous à améliorer ces guides en donnant vos impressions!"
getstarted: "Commencer"

Thanks again

**Comment by kateregga1** [comment]
Thanks Nick,

I will go for option C by following the detailed explanation of the translation work flow.

I am beginning with Introduction and Beginner units as I get used to the workflow.

**Comment by althio** [comment]
Hi @kateregga1 

Thank you so much for starting this translation. I am sure this language will be much useful for several communities for training, for local and for remote mapping.

If you have any kind of technical difficulties with GitHub or prose.io please do contact us here or at learnosm-coord[@]openstreetmap.org and we will try to help as best and as quickly as we can.

**Comment by kateregga1** [comment]
@Nick-Tallguy here is the translation for the text

en:
tagline: "Learn OpenStreetMap Step by Step"
contribute: "Help improve our guides"
trainingspan: "Are you a workshop organizer?"
training: "Check out training material for this guide (in English)"
feedbackspan: "Was this chapter helpful?"
feedback: "Let us know and help us improve the guides!"
getstarted: "Get started"

sw:
tagline: "Jifunze OpenStreetMap Hatua kwa Hatua kwa Hatua"
contribute: "Saidia kuboresha maelezo yetu"
trainingspan: "Je, wewe ni muhamashishaji wa mafunzo?"
training: "Tazama nyenzo za kujifunza (kwa Kiswahili)"
feedbackspan: "Sura hi imekusaidia?"
feedback: "Tufahamishe na tushaidie kuboresha muongozo!"
getstarted: "Anza"

**Comment by kateregga1** [comment]
Hi @Nick-Tallguy @althio 

I would like to start on the translation following this guide 
https://github.com/AmericanRedCross/Guides/blob/master/TranslationWorkflow_LearnOSM/translatorWorkflow.md 

Checking the folder list, Swahili has not yet been added to the folder list. Please let me know when it is added so I can proceed, thanks

**Comment by Nick-Tallguy** [comment]
Hi,

It's at https://github.com/hotosm/learnosm/tree/gh-pages/_posts/sw

Nick
(OSM=Tallguy)

dodgy didgits as using a phone with a spell chequer.

Humanitarian OpenStreetMap Team Member

**Comment by althio** [comment]
If you want to try with prose.io the link should look like:
http://prose.io/#kateregga1/learnosm/tree/gh-pages/_posts/sw

**Comment by Nick-Tallguy** [comment]
Hi,

Using my phone so may be wrong but I think your fork of the site is at
least one update behind the main site.  You may need to do a pull request.

I can see that the sw folder is not in your repository yet.

Nick
(OSM=Tallguy)

dodgy didgits as using a phone with a spell chequer.

Humanitarian OpenStreetMap Team Member

**Comment by kateregga1** [comment]
Hi Nick,

What exactly do I translate on this section?

https://github.com/hotosm/learnosm/edit/gh-pages/_posts/sw/0100-01-01-status.md

layout: default
permalink: /sw/status/
lang: sw
title: Translation Status
nosearch: true
---

## Translation Status - All Languages

- [Spanish]({{site.baseurl}}/es/status/)

**Comment by althio** [comment]
I would say nothing, it is a bogus page as far as I know.

**Comment by kateregga1** [comment]
How do I continue with  translating the other sections in the Beginner's Guide?

I would also like to use Prose.io via http://prose.io/#kateregga1/learnosm/tree/gh-pages/_posts/sw

But I can't find anything in the Swahili folder

**Comment by Nick-Tallguy** [comment]
Hi,

Sorry,

Nothing to translate on that one!

Nick

On 20/05/15 16:18, Geoffrey Kateregga wrote:
>
> Hi Nick,
>
> What exactly do I translate on this section?
>
> https://github.com/hotosm/learnosm/edit/gh-pages/_posts/sw/0100-01-01-status.md
>
> layout: default
> permalink: /sw/status/
> lang: sw
> title: Translation Status
>
>
>     nosearch: true
>
>
>     Translation Status - All Languages
>
>   * Spanish <%7B%7Bsite.baseurl%7D%7D/es/status/>
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/hotosm/learnosm/issues/359#issuecomment-103923156>.
>


-- 

Nick

Volunteer 'Tallguy' for 
https://wiki.openstreetmap.org/wiki/Humanitarian_OSM_Team

http://www.openstreetmap.org/user/Tallguy

**Comment by Nick-Tallguy** [comment]
Geoffrey,

I've never used the Prose.io option, but looking in your folder there, I 
agree that the files are not there at the moment. I don't know how, but 
you need to update that repository.

Regards

Nick

On 20/05/15 16:44, Geoffrey Kateregga wrote:
>
> How do I continue with translating the other sections in the 
> Beginner's Guide?
>
> I would also like to use Prose.io via 
> http://prose.io/#kateregga1/learnosm/tree/gh-pages/_posts/sw
>
> But I can't find anything in the Swahili folder
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/hotosm/learnosm/issues/359#issuecomment-103932979>.
>


-- 

Nick

Volunteer 'Tallguy' for 
https://wiki.openstreetmap.org/wiki/Humanitarian_OSM_Team

http://www.openstreetmap.org/user/Tallguy

**Comment by Nick-Tallguy** [comment]
@kateregga1 your work is in demand - the site analysis software shows there have been 138 pageviews of the Swahili section since you started!

Keep up the good work & thank you!

Nick

**Comment by kateregga1** [comment]
@Nick-Tallguy @althio I need to continue with the translation but I cant find any more files here to translate https://github.com/hotosm/learnosm/tree/gh-pages/_posts/sw 

How can I access the other files in the Beginner's Unit?

**Comment by Nick-Tallguy** [comment]
@kateregga1 there are 3 files ready for translation in the 'beginner' folder at that location - this is one of them https://github.com/hotosm/learnosm/blob/gh-pages/_posts/sw/beginner/0200-12-29-start-osm.md  let me know if still having a problem.

Nick

**Comment by Nick-Tallguy** [comment]
@kateregga1 nice work thanks. I've merged all your updates, and have put some more files in the folder ready for you to translate.  
 Could you also go back over the old files - after you've updated or refreshed, because I've amended the links at the bottom & translating the names would make it look better. If you can translate the title of the files - where it reads  **title: Introduction** - please translate the word '**Introduction**', and translate the title for each of the other files - use the same word(s) in the links at the bottom of the files.

At the moment all the files point to the 'neutral' or English images - this is fine for most of the images & files, but in some places you may wish to use more local images. The easiest way of getting the images into the system is to email them to me & I'll sort them out and add them in - make it easy for me be letting me know where you want it to be please. If you can adjust the image size to no more than 520 pixels on the longest side, that helps, but if you can't don't worry, I will sort it out. 

Hope this makes sense - let me know if any problems. 

Keep up the good work

Regards

Nick

**Comment by Nick-Tallguy** [comment]
@kateregga1 its all looking good so far. Looks much better after your recent updates. Keep up the good work and let me know if you need any help at all.

Nick

**Comment by Nick-Tallguy** [comment]
@kateregga1 please make sure you update your repository / fork - I've just implemented some large movements of files. Nothing is deleted, but some topics are now in different folders. 

There is also a 'staging site' at https://github.com/Nick-Tallguy/Nick-Tallguy.github.io on which I test out changes before implementing them. I keep both up to date. I don't mind which one you work on, but if you are in any doubts you can always work on the staging site, on which I can give you collaborator rights. On the staging site you can them make your changes, view them, and when you are happy that they display correctly, let me know & I pass them on to the main site. 

I don't mind which method we use - I will keep everything in sync as needed.

Regards & thanks for your work on this.

Nick

**Comment by Nick-Tallguy** [comment]
Hi @nuruk & @kateregga1 I've merged the changes to beginner & josm and they are now visible on the site. It looks good to me, but can you check I've formatted everything okay please - bit difficult for me as I don't speak the language!

It may be easier if you change over to translating from https://www.transifex.com/hotosm/learnosm-1/dashboard/ as you will always be working from the most up to date files and no updating is required by you. There are also a couple of button labels etc within essential_setup.txt which I could use to update LearnOSM so the homepage etc. has the correct labels. There is no need to traqnslate again anything that has already been done, but do please have a quick check to make sure there are no small updates that need translating. 

But, if you prefer to keep working in github, I'll work with you and we'll update it all this way.

Kind regards & thanks for submitting these updates.

Nick

**Comment by Nick-Tallguy** [comment]
@kateregga1 & @nuruk for your info http://learnosm.org/en/beginner/id-editor/ contans far more than http://learnosm.org/sw/beginner/id-editor/

Regards

Nick

**Comment by kateregga1** [comment]
Thanks @nick we tried to use transfex but realised the pages we had translated at the start were displayed as untranslated. Also transfex doesnt allow us to translate a paragraph of text. When translating into swahili, many times its necessary to change the order of the words to make a make a meaningful sentence.

We would like to continue with the work using Github.

**Comment by Nick-Tallguy** [comment]
Okay, no problem.  

I haven't found a way of updating Transifex to the effect that only some translations are needed for a particular module - I guess if we had used it right from the start this wouldn't have been an issue. 

We need to work out a method of checking the Kiswahili section in comparison with the English. For instance http://learnosm.org/en/beginner/id-editor/ was created by combining two sections, but http://learnosm.org/sw/beginner/id-editor/ has only the introduction to iD. 

How would you like me to set things up for other modules for translation? I can put an English version of a module into the Kiswahili folders, so your team continues using the same method they have used up to now (as long as they keep their fork in sync everything should be okay). Or if you have another method in mind, let me know. 

Regards

Nick

**Comment by Nick-Tallguy** [comment]
Although we'll work with translations through github, it would help me a lot if the phrases in https://www.transifex.com/hotosm/learnosm-1/essential_setuptxt/ were translated - although many have been done in the past, there are quite a few missing, and they are the phrases for 'button labels' and other bits within the site, which will improve things a lot. 

For instance, the green button at the bottom of this page  http://learnosm.org/sw/beginner/  should contain the phrase 'Get Started'.

Also the text for the yellow & blue buttons on the front page need translating.

I can paste the contents of the file into an issue here, if that would be the easiest way forward?
Regards

Nick

**Comment by kateregga1** [comment]
Hi Nick, would you please put the English modules into the Kiswahili folders, so that our team continues using the method of translation that we are used to.

**Comment by Nick-Tallguy** [comment]
Hi,

I'm in the process of putting some files into the folder for your team to work on - they should appear within the next couple of hours;  

**Beginner**  
-  iD_editor - this was rewritten and the new version needs translating (I've renamed the old version 'draft' so that it doesn't display, but you can refer to it if needed),
-  Glossary,  
-  Moving Forward.  

**JOSM**  
-  JOSM-Tools,  
-  JOSM-Plugins  

If there is something in particular that you want prepared for translation, let me know & I'll sort it out.

Could you, or one of your team, please translate the following phrases;  
-  Get started =  
-  Humanitarian Mapping =  
-  Remote mapping information =  
-  More guides =  
-  Guides in Document format =  

Thanks for your work on this.  

Regards  

Nick

**Comment by kateregga1** [comment]
Hi Nick, here are the translations for the phrases

Get started = Anza 

Humanitarian Mapping =Kutengeneza Ramani kwa Kujitolea

Remote mapping information = Taarifa za kutengeneza ramani ukiwa mbali

More guides = Miongozo zaidi

Guides in Document format = Miongozo katika mtindo wa Nyaraka

**Comment by Nick-Tallguy** [comment]
Geoffrey,

Thanks for that - these will appear on the site within a couple of days. 
There are a few more from other bits of the site that could do with 
translating when you have time - I've done the bottom one using 'Get 
Started', but the ones above need doing.

tagline: "Learn OpenStreetMap Step by Step"
     contribute: "Help improve our guides"
     trainingspan: "Are you a workshop organizer?"
     training: "Check out training material for this guide (in English)"
     feedbackspan: "Was this chapter helpful?"
     feedback: "Let us know and help us improve the guides!"
     getstarted: "Anza"

Thanks in anticipation

Nick

**Comment by kateregga1** [comment]
tagline: "Jifunze OpenStreetMap hatua kwa hatua"
contribute: "Saidia kuboresha miongozo yetu"
trainingspan: "Je wewe ni muaandaaji wa mkutano?"
training: "Angalia mafundisho ya huu muongozo(kwa kiingereza)"
feedbackspan: "Je hii sura ilikuwa na manufaa?"
feedback: "Tujulishe na utusaidie kuboresha miongozo!"
getstarted: "Anza"

**Comment by Nick-Tallguy** [comment]
All on the site now - looks much better now. Thanks for your work on this.

**Comment by Nick-Tallguy** [comment]
Closing as successful. Translation on site. If someone wishes to continue they can use this process or use Transifex where we have improved our process
