### ISSUE TITLE
Review language codes

### ISSUE THREAD

**Issue by althio** [hotosm/learnosm#362]
According to http://en.wikipedia.org/wiki/List_of_ISO_639-1_codes

Indonesian  Bahasa Indonesia    `id` (instead of `bi`)
- [ ] code `bi` to `id`
- [ ] `_posts/id`
- [ ] `/images/bi/`

Japanese    日本語 (にほんご)    `ja` (instead of `jp`)
- [x] code `jp` to `ja` https://github.com/Nick-Tallguy/learnosm/commit/62ac9b41557a6a17d13ac3de0514132712c91807
- [x] _posts/ja https://github.com/Nick-Tallguy/learnosm/commit/ccd8dffc4b00c452839316ffda21e366e36b6682
- [ ] `/images/ja/`

**Comment by Nick-Tallguy** [comment]
You're right. We need to change each of the existing files for these languages or they will not be visible as soon as #361 comes live. 
I'll start working on it now. I'd rather we sort all the sections properly, but it will mean a little work.

**Comment by Nick-Tallguy** [comment]
I've changed all of the Japanese files. Nearly all of the site was in Japanese as well so quite major.

Not done Indonesian Bahasa Indonesia id (instead of bi) as that is not in your current change. Not sure how much of the site will need changing.

**Comment by althio** [comment]
Japanese	日本語 (にほんご)	`ja` (instead of `jp`)
 - [x] code `jp` to `ja` #361
 - [x] _posts/ja #363

**Comment by Nick-Tallguy** [comment]
I've changed jp to ja - these 3 files are involved in anything to do with languages. 

LearnOSM/all-translation.json
LearnOSM/_config.yml
LearnOSM/_layouts/default.html

The images are still in a folder 'ja' but that can wait until we review later.

**Comment by althio** [comment]
Thank you @Nick-Tallguy for the excellent job so far!

**Comment by Nick-Tallguy** [comment]
Presumably also need to make alterations in the Japanese words.

Japanese 日本語 (にほんご) ja (instead of jp)

**Comment by Nick-Tallguy** [comment]
Also need to sort out Norwegian translation code. 'no' is interpreted as 'false' and some files do not display. need to change the two letter code away from 'no'

**Comment by althio** [comment]
Hi @Nick-Tallguy 

Do you have the time to try three or more letter codes?
It that works, it could be useful for pt-BR, zh-? and we could use that for nor or no-NO?

**Comment by Nick-Tallguy** [comment]
@althio have spent a long time trying options with 3 letter codes, capitals and getting nowhere. However a quick check on http://en.wikipedia.org/wiki/List_of_ISO_639-1_codes shows that Norwegian also uses the code 'nb'
On my local version I've changed the folder and all needed files to point to 'nb' and it all works. 

Suggest we change to 'nb' instead of 'no'. 

I have all changes on my computer and could submit a pull request fairly easily to change them all if you are happy with this.

**Comment by althio** [comment]
Thanks for trying @Nick-Tallguy that is rather unfortunate for a few things I had in mind.
Anyway...

**Comment by michael63-osm** [comment]
I just made the change for Indonesian from 'bi' to 'id' on the staging site and will now close this issue. Just let us keep in mind (if the recent language request for Greek is to be accepted) that the ISO code for Greek is not 'gr' but 'el' ...
