### ISSUE TITLE
mobile-mapping - OsmAnd and OSMTracker pages review

### ISSUE THREAD

**Issue by althio** [hotosm/learnosm#374]
http://learnosm.org/en/mobile-mapping/

@bgirardot wrote:
> We are making a lot of progress on a long term goal of getting more data back from other humanitarian org people active in the field.
>
> We have a real chance to put in place a major cooperative program and data exchange with the UNMEER group operating in W. Africa.
>
> Right now they are field trailing OsmAnd and OSMTracker but one of their big hurdles is lack of documentation.
>
> We are pointing them to LearnOSM, could we please review those pages specifically and make sure they are up to date and complete?

'John Hubbard' via LearnOSM <learnosm@hotosm.org> wrote:
Subject: How to use OsmAnd
> Great tutorial, but are you going to update for the new version with the totally different UI?

In case that helps for the time being:
http://osmand.net/blog?id=osmand-2-0-released

**Comment by gitGOwin** [comment]
I'm writing an update for the latest OsmAnd UI (2.0+) and hope to post a pull request soon. The new UI is definitely a step up in the UX department!

**Comment by Nick-Tallguy** [comment]
I've nearly finiished the section on OSMTracker - hoping to upload later today.

**Comment by althio** [comment]
Great @gitGOwin and @Nick-Tallguy

**Comment by Nick-Tallguy** [comment]
@gitGOwin whilst researching something else, I found a link on [this page](http://wiki.openstreetmap.org/wiki/Field_Papers) on how to use OSMand and Field Papers. Looks as if would be worth mentioning in some way.  

Regards  

Nick

**Comment by gitGOwin** [comment]
@Nick-Tallguy , thanks for the heads-up. I'll look into how I can incorporate this. I'm more than halfway through the new docs, but other commitments are keeping me away from completing it. Will upload as soon as I can.

**Comment by gitGOwin** [comment]
I have a PR #382 for a new material for OsmAnd, based on 2.x.

**Comment by Nick-Tallguy** [comment]
#384 completes this - OsmAnd 2 now updated.

**Comment by Nick-Tallguy** [comment]
#397 updates section moving images to comply with #306.

@gitGOwin do you still have your original screens hots please? For future translations it would be good to have images without English labels so we can use the same image in all languages.

**Comment by gitGOwin** [comment]
@Nick-Tallguy . That's a very good idea. 

Yes, I do. Please let me know where I should put them up for re-use.

**Comment by Nick-Tallguy** [comment]
@gitGOwin could you please add them to images/mobile-mapping  
If you can use the same format for the file name - pair them with the labelled version, so for instance
existing = osmand2_001a.png
new = osmand2_001a_no_label.png

eventually we need to be in the position of having  

1.  either images with no labels but numbers on them, so that the text in the .md file identifies the number to the function. This way we have images that can easily be reused, or  
2.  image format of  
osmand2_001.png  
osmand2_001.bi.png  
osmand2_001.de.png  
osmand2_001.en.png  
etc..

We've got plans to update the wiki etc.  so this is obvious to contributors - at the moment it is not.

**Comment by gitGOwin** [comment]
I have reservations about the use of numbers. I know it makes images more flexible, but I'd like images to be more useful in one glance.  Besides, wouldn't using an app in another language show many interface elements in that language, too? I'll try to revise the file naming scheme for the English guide as soon as I have the time.

I will also release the raw SVG file, with the embedded images so they may be used by others.

**Comment by Nick-Tallguy** [comment]
@gitGOwin 

Thanks for that - I share your reservations.

Thanks for all your work on this.

Nick

**Comment by Nick-Tallguy** [comment]
@nguillaumin - we have a complimentary guide within LearnOSM at http://learnosm.org/en/mobile-mapping/osmtracker/ just in case it is of any use to you. Our aim is to get it translated to other languages - can't give you a timescale on that at the moment.

**Comment by nguillaumin** [comment]
Nice work, thanks for the information!

**Comment by Nick-Tallguy** [comment]
Closing - both sections now exist with cross references included in earlier comments.
