### ISSUE TITLE
nl section of site - delete & start again in the future?

### ISSUE THREAD

**Issue by Nick-Tallguy** [hotosm/learnosm#398]
@althio & any other interested parties. Whilst tidying the site I've found 3 files in a 'nl' folder. There are also several images which relate to those files (although the images are actually english images & duplicates of existing ones). The three files do not have the correct header information to display on the site in their current format.
Since the files were created, the site has been updated & they are out of date. 

My opinion at the moment is to delete them & the images that relate to them. When we have a translation process up & running it will actually be easier to start the 'nl' section from scratch, translating current files.

Before I delete them & the associated images, does anyone have any strong views to the contrary (& are they willing to do the work to make them appear on the site?)

**Comment by althio** [comment]
OK for clean up and remove the clutter.
It will be transparent on the main site anyway.
