### ISSUE TITLE
All chapters - move to head of index, delete it, or leave as is?

### ISSUE THREAD

**Issue by Nick-Tallguy** [hotosm/learnosm#416]
If you visit http://learnosm.org/en/beginner/ you will find at the bottom of the section index on the left side the heading 'all chapters'. This produces an amalgamation of all of the subjects within the beginner section, which could be useful to someone reading through the beginners section from beginning to end.  

However, my experience of it when I read through the beginners section was - I didn't discover it, or it's function until I had read all of the preceding chapters .....doh!  

On the basis that I would like to see the index shortened, and you can happily navigate without it, personally I would like to see 'all chapters' removed from the beginners section in all languages.  But that's just my opinion - I do think that if we are going to keep it, it should be at the head of the index on the left so at least you will tend to make use of it if working your way through the index. To help you form an opinion, I've started putting 'all chapters' at the head of the index on this staging site  

http://nick-tallguy.github.io/en/

where all chapters appears at the head of the index of the beginners guide for en, bi & de languages - I will add others when I get the chance, so it may be on more languages by the time you read this. Due to the way it formats, you do get a little technical 'mess' part way through reading the site using it - sorry, I don't know how or if this can be hidden.

I'd appreciate anyone reading this adding a comment below as to whether they thing we should keep all chapters, delete it, have it at the head of the index, or leave it at the bottom.  
Thanks for reading.

**Comment by SteveBower** [comment]
Nick,
I agree on removing "all chapters". It seems redundant to me, other than
being able to easily search "all chapters", which I doubt is of much use.
If not removed, move to the top.

~~Steve

**Comment by althio** [comment]
I think it was not added for navigation purpose but for ease of print for
the whole section.
I dislike the redundancy here.

My vote is: delete it.

But we need offline/printable material with automatic generation. One-click
download package with a full section would be a plus.

**Comment by Nick-Tallguy** [comment]
@althio I can't do 'automatic generation', but once we are satisfied we have the beginner section cut down to just a beginner section, I could produce an .odt amalgamation and .pdf, and it could be (for instance) downloaded by clicking on a link from the http://learnosm.org/en/beginner/ page.

**Comment by Nick-Tallguy** [comment]
All Chapters has been removed
