### ISSUE TITLE
New Translation into Simplified Chinese (ZH)

### ISSUE THREAD

**Issue by qyu** [hotosm/learnosm#426]
Hello there,
I am trying to translate learnosm.org into Simplifed Chinese (ZH) through Prose. Can you add me as a collaborator? 
Thank you.
Ching

**Comment by althio** [comment]
Hi @qyu 

Thank you very much for starting this valuable work!

Are you familiar with GitHub/git? We generally receive contributions through pull requests and we review and merge them so you don't need collaborator rights on this repository.

We are reorganising the website right now so we might ask you to be patient while the files are made available for you in prose.io. Alternatively I would encourage you to start translating locally if you can.

@Nick-Tallguy 
Do you think we should direct translators to the staging site repository?
It is very new so it is not documented in our workflow.

**Comment by Nick-Tallguy** [comment]
Althio,

I think it would be better on the staging site - I'm going to be time 
hungry for a few days now - either can you set it up on the staging 
site, or I can do it in a few days.

Nick

On 10/06/15 22:15, althio wrote:
>
> Hi @qyu <https://github.com/qyu>
>
> Thank you very much for starting this valuable work!
>
> Are you familiar with GitHub/git? We generally receive contributions 
> through pull requests and we review and merge them so you don't need 
> collaborator rights on this repository.
>
> We are reorganising the website right now so we might ask you to be 
> patient while the files are made available for you in prose.io. 
> Alternatively I would encourage you to start translating locally if 
> you can.
>
> @Nick-Tallguy <https://github.com/Nick-Tallguy>
> Do you think we should direct translators to the staging site repository?
> It is very new so it is not documented in our workflow.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/hotosm/learnosm/issues/426#issuecomment-110916792>.
>


-- 

Nick

Volunteer 'Tallguy' for 
https://wiki.openstreetmap.org/wiki/Humanitarian_OSM_Team

http://www.openstreetmap.org/user/Tallguy

**Comment by qyu** [comment]
Hi @althio,
I am familiar with Git. I'll just work on it locally. : )
Ching

**Comment by Nick-Tallguy** [comment]
@qyu please make sure you update your repository / fork - I've just implemented some large movements of files. Nothing is deleted, but some topics are now in different folders.

**Comment by Nick-Tallguy** [comment]
Closing this as translation is ongoing using Transifex.

**Comment by Nick-Tallguy** [comment]
see Transifex workflow
