### ISSUE TITLE
text overflowing little boxes on the learnosm.org homepage

### ISSUE THREAD

**Issue by harry-wood** [hotosm/learnosm#446]
On the learnosm.org homepage, I guess somebody tried to cram some more text in these little boxes recently. Looks yucky at certain narrowish window widths.

![learnosm-overflowing-text](https://cloud.githubusercontent.com/assets/227525/8988567/dc591aae-36de-11e5-8186-0ed734192081.png)

Could be some CSS tricks to fix this, but I suggest we just have a bit less text there (remove the bits in brackets) and try to discourage adding text somehow (the eternal "wiki problem")

**Comment by Nick-Tallguy** [comment]
Proposed version visible on http://nick-tallguy.github.io/en/ (all languages have been changed). Unless there is a major problem this will be passed onto the main LearnOSM site within a day or so.

**Comment by Nick-Tallguy** [comment]
Resolved now - all languages updated http://learnosm.org/en/
