### ISSUE TITLE
Update the beginners guide for iD to emphasize that deleting others work should be a last resort

### ISSUE THREAD

**Issue by bgirardot** [hotosm/learnosm#461]
As per a discussion on OSM-Talk, with great power, comes great responsibility, and the delete function in iD that new mappers are likely to encounter is great power. We should explain that deleting other people's work destroys their contributions and the history of the item in question, they should modify rather than delete.

I will try and get this part updated, but wanted to record the issue so it does not get lost.

**Comment by bgirardot** [comment]
Here is my proposed change, a small note box after "Delete" is first introduced. This seems like the most minimal change that would not affect translations too much as it doesn't change any existing text, only adds a few sentences. Nick, if you approve, I'll make a pull request to the staging site. If not, no problem, I understand it is a more significant page to change than GPSLogger :) But I do agree with the email thread, it would be good for mappers and the OSM database in general to let new mappers know deleting should be a last resort.

![2015-08-25_18h58_23](https://cloud.githubusercontent.com/assets/265831/9473520/8c58d33c-4b5b-11e5-9d11-bfc960f6a3bb.png)

**Comment by Nick-Tallguy** [comment]
@bgirardot I agree with your comments and solution - looks good to me, and as you say the effect on Tranisfex would be minimal.

**Comment by Nick-Tallguy** [comment]
Has been dealt with on earlier pull request - there is now a section within iD
