### ISSUE TITLE
Task Creation in Task Manager - section to be added

### ISSUE THREAD

**Issue by Nick-Tallguy** [hotosm/learnosm#482]
Add guide by Dan Culli on how to create a task within Tasking manager to learnOSM - https://docs.google.com/document/d/1zykWGHN1w6ODY13k2uT-bnQZmj7XBGkD7j6cgtzeZA8/edit#heading=h.uwwdk9ptec41

**Comment by Nick-Tallguy** [comment]
Initial doc created as https://github.com/hotosm/learnosm/blob/gh-pages/_posts/en/coordination/draft0500-10-24-tasking-manager-admin.md  needs text etc adding.

**Comment by geomantic** [comment]
@Nick-Tallguy I forked the project and have made some edits to this section. What's the best way to get it to the HOT Tr WG for review? I can submit a pull request or...? Suggestions?

**Comment by Nick-Tallguy** [comment]
Hi @geomantic thanks for taking this on. Probably easiest to submit a pull request - it can be viewed there before merging.
There is also another version that I started to create, can be seen at https://github.com/Nick-Tallguy/Nick-Tallguy.github.io/blob/master/_posts/en/coordination/draft0500-10-24-tasking-manager-admin.md
Regards
Nick

**Comment by geomantic** [comment]
Hi @Nick-Tallguy, I just created a pull request but I got a warning about conflicts. Maybe it's as simple as not having write access to the repo? At any rate, please let me know if you need my help to resolve. Best, 
Steven

**Comment by Nick-Tallguy** [comment]
Closing as TM Admin is on site now
