### ISSUE TITLE
0100-01-01-index.md

### ISSUE THREAD

**Issue by sabas** [hotosm/learnosm#490]
Does this line miss a full stop or an exclamation mark after "learn how"?
`Anyone can edit OpenStreetMap. Here you can learn how LearnOSM provides easy to understand,`

**Comment by jmarlena** [comment]
@sabas I agree that the frontintro in [0100-01-01-index.md](https://github.com/hotosm/learnosm/blob/gh-pages/_posts/en/0100-01-01-index.md) reads a lot easier as:  `Anyone can edit OpenStreetMap. Here you can learn how. LearnOSM provides easy to understand, step-by-step guides for you to get started with contributing to OpenStreetMap and using OpenStreetMap and using OpenStreetMap data. If you are interested in running an OpenStreetMap workshop, check out the LearnOSM trainer resources.`

**Comment by jmarlena** [comment]
I understand this is a minor edit that can be done in GitHub according to the [contributing guidelines on text modifications](https://github.com/hotosm/learnosm/blob/gh-pages/CONTRIBUTING.md#text-modifications). @althio Can you or someone else in this repo create a "newcomer bug fix" or "first bug" label for this?

**Comment by Nick-Tallguy** [comment]
Closing as done
