### ISSUE TITLE
bigger font, take more screen real estate

### ISSUE THREAD

**Issue by d3netxer** [hotosm/learnosm#496]
relates to #33 

some suggestions to consider:
- decrease of the padding (.padAll)
- increase main font size to 17px for the main content section
- keep font size of side menu the same
- for the main content section change the margin-left to around 38% and

**Comment by Nick-Tallguy** [comment]
@d3netxer I've implemented a couple of small changes to 'style.css' on the staging site - changed several of the font size settings and reduced much of the padding - padall and others.  Thanks for the inspiration on these.

**Comment by Nick-Tallguy** [comment]
Closing now. I think I've implemented all of these suggestions
