### ISSUE TITLE
kramdown replaces rdiscount

### ISSUE THREAD

**Issue by Nick-Tallguy** [hotosm/learnosm#498]
GitHub is changing the markdown style that it uses from rdiscount, which all of LearnOSM has been written in, to kramdown. GitHub article explaining this <https://github.com/blog/2100-github-pages-now-faster-and-simpler-with-jekyll-3-0>

[kramdown home](http://kramdown.gettalong.org/)
[Syntax](http://kramdown.gettalong.org/syntax.html)

It shouldn't make too much difference and in the long run will improve some things. But...... some of our headers don't seem to be making the transition too well and we may have to go through the sections doing a little updating before we implement the change on the main site. Essentially you now need a space between the # and the header text.

[Nick's staging site - HOT remote mapping for instance](http://nick-tallguy.github.io/en/coordination/HOT-Remote-Response-Guide) you'll notice that the heading is no longer displayed as a heading - not green or bold.The indexing still works (the site only searches the titles).

I've also now realized that some numbered lists may be affected - pull request #497 has just brought this to my attention. 

No great thing I hear you say - but if you click the language sections at the top I think you'll find that the problem now exists in all of the languages!

Need to make sure that any pull requests we authorise in between don't implement kramdown until we are ready - may happen if Gemfile is updated - I'm not sure on this and am willing to be corrected. 

## Suggested order for sorting this out.
1.   Update the English version
2.  Upload the English version to Transifex (so we don't get more problems as we work!)
3.  Go through the languages & update them - I've added a tab to the audit site spreadsheet - [read only link](https://docs.google.com/spreadsheets/d/1NlJHTYAYpyyF5o9D8UMAsSzFG7lHY2cIi2mzncx530w/edit?usp=sharing)
4.  When all is done we update config.yml to show kramdown instead of rdiscount (two lines to alter in the file).

**Comment by Nick-Tallguy** [comment]
Also just realised that highlighter needs to change from pigments to rouge - have made this change on staging site & am testing now.

**Comment by Nick-Tallguy** [comment]
# Workflow I'm now following;  

1.  Have created a branch called 'kramdown_amendments' for main LearnOSM site & I will be working on that branch - do not merge this into the main gh-pages site or authorise any pull requests which are in the branch - we will do this when all files are ready.  
2.  kramdown & rouge are now in use on the staging site at <http://nick-tallguy.github.io/en/> so we can view modules there to see if they are displaying correctly or if any action is required with them.  
3.  I check each of the English versions of a module on the staging site, checking to see if the heading is okay, if the numbered paragraphs are okay, or if there are any other display or other issues.  
4.  Once a module has been viewed on the staging site, the spreadsheet at <https://docs.google.com/spreadsheets/d/1NlJHTYAYpyyF5o9D8UMAsSzFG7lHY2cIi2mzncx530w/edit?usp=sharing> should be updated to show that either;  
    - the module is all okay (change the cell colour to green)  
    - the module requires amending (change the colour to orange) or,  
    - the module has been amended & [Transifex](https://www.transifex.com/hotosm/learnosm-1/dashboard/) now has the updated module if needed - Transifex will only need updating if the English module is changed.  
5.  Once all of English is complete I will move onto another language.  

## If anyone could help with any of these processes I would be grateful.  

You may need to request permission to edit the audit spreadsheet. Help can be in two stages;  
1.  Does not require any special skills - view a module on the [staging site](http://nick-tallguy.github.io/en/] & update the spreadsheet to show that something needs doing - perhaps add a cell note so we know what is required.  
2. Requires GitHub skills to make any amendments needed - remember to use a branch such as 'kramdown_amendments' so that we can wait & then make the merge when all is complete.

**Comment by althio** [comment]
@Nick-Tallguy 
Thanks again for all the work and attention to details here.
I won't be able to help anytime soon :( but I am still trying to read and catch up whenever I can.
I acknowledge and understand that you want to prepare, wait, and merge when all is complete.

**Comment by Nick-Tallguy** [comment]
All modules that are on Transifex for translation are now updated - some with minor amendments that will require translation.

Now at the stage where any translations that are down will be with the formatting that is required for use with kramdown - the more the translators do, the better for us. In fact it may be the easiest policy for other languages to just download the module again from transifex rather than reformat an existing translation. 

I'll work on the remaining English versions as well as downloading from transifex & adding them - will only done the ones that have been completed by translators. I think our efficient Nederlands translator has done many of them since yesterday alread.

**Comment by Nick-Tallguy** [comment]
I think all of the files that had been affected are now updated. I've sent a message to the translators so they are aware of the changes and giving the opportunity for checking on the status. To see how all of the files will look now, see 

http://nick-tallguy.github.io/en/

I believe the pull request relating to this issue can now be merged at whichever point is convenient to us. I will leave it a few more days just in case someone makes contact with something that needs updating, but I think if they do, it will only be something minor anyway.

**Comment by Nick-Tallguy** [comment]
Closing this issue now - there may still be formatting errors that have slipped through the net, cut a recent pull request awaiting action by me by @SteveBower looks to have captured all of them.
