### ISSUE TITLE
dead links on learnosm.org/en/osm-data/getting-data/

### ISSUE THREAD

**Issue by althio** [hotosm/learnosm#501]
from feedback at learnosm.@.hotosm.org

>I noticed that on http://learnosm.org/en/osm-data/getting-data/, the link to "JOSM Presets" in the "Customized Extracts" section gives me a 404 error.

>You might also be interested in knowing that farther up the page, under "Metro Extracts," the link to "Another website created by Michal Migurski" works, but the page it brings me to tells me the collection is no longer maintained. It provides a link (https://mapzen.com/metro-extracts/) to a newer version of metro extracts but I get 404'd by that link! Searching for Mapzen metro extracts through Google, I have located the link you may want to place in your learnosm page: https://mapzen.com/data/metro-extracts/.

**Comment by SteveBower** [comment]
Benoît - Thanks for forwarding this feedback - I will follow up on this.

Cheers,
~~Steve

**Comment by Nick-Tallguy** [comment]
Nice work @althio & @SteveBower - closing this now.
