### ISSUE TITLE
QGIS sample data is missing

### ISSUE THREAD

**Issue by bennyistanto** [hotosm/learnosm#504]
Hello,

I would like to use some QGIS materials from English Learning Guides - https://github.com/hotosm/learnosm/wiki/English-Learning-Guides and I couldn't find the QGIS sample data (beginning-qgis-sample.zip) that are mention in the following docs: https://docs.google.com/document/d/1MGrZZEYr8xYtveeo0hER3HbjfqmQhAONtDSRmWCtKPM/edit

Thank you
B

**Comment by althio** [comment]
Hello @bennyistanto

That document is certainly outdated, please try instead
http://learnosm.org/en/osm-data/osm-in-qgis/
and we would appreciate your feedback again.

**Comment by bennyistanto** [comment]
Thank you
