### ISSUE TITLE
Update _config.yml & running the site locally with 'jekyll serve -w'

### ISSUE THREAD

**Issue by Nick-Tallguy** [hotosm/learnosm#505]
Hi @jmarlena 

I've just carried out some updates on my computer & realised I had made a mistake and was running an old version of ruby, which was causing some problems - in particular your update in #493 would now appear perfectly correct to me.

At the moment I have just carried out the update on my 'staging site', in commit https://github.com/Nick-Tallguy/Nick-Tallguy.github.io/commit/dd51136144cc3820084722fca758912b0412fd66
but I intend to add it to this full site shortly.

I am now running the site locally using **Jekyll serve -w**

If I have got any of the other configuration settings wrong, please let me know - I'm self taught & could easily be making mistakes through ignorance. - I'd rather be told so I can sort it out!

Thanks again for your work in setting up the 'help guides'

Regards

Nick

**Comment by jmarlena** [comment]
Hey @Nick-Tallguy! Sorry for the delay. I haven't been managing my notifications for learnosm well so I  nearly missed this message. I will take a look at some of these configuration settings on Friday, as it's "open source" day at work. :wink: Also, currently I am doing some more research on GitHub Pages so I am hoping I'll learn more about how to get learnosm.org up-to-date. :wink: Thanks for following up with me.

**Comment by Nick-Tallguy** [comment]
Closing - testing site at http://nick-tallguy.github.io/en/ can also be used, allows those who do not run the site locally to see how their changes will appear. 

>Note  
I'm currently running Mint 18.3 (based on Ubuntu 16.04) and to get full functionality locally I have to use 'RVM' to install a recent version of ruby, then ruby gems will install correctly.
