### ISSUE TITLE
increase img size 

### ISSUE THREAD

**Issue by d3netxer** [hotosm/learnosm#506]
I would like to propose to increase the maximum img size. Maybe to a width of 800. I assume the current limit is because of we want want the storage of all the images to be too big. However, many of the images are screenshots, and often 520 pixels does not give a screenshot justice.

**Comment by Nick-Tallguy** [comment]
Hi,

I think that LearnOSM would benefit from larger images in some sections.

I wasn't involved in setting up LearnOSM, but I think it's main aim was to provide multi-language, simple instruction, for anyone new to OSM, especially if they were in an area of poor internet connection. I think we can still hold true to that, for those sections that need it.

Many of the people who are visiting the site are trying to learn how to map remotely, & are intending to trace from satellite imagery - they don't have a problem with bandwidth, and they would benefit from help using;
* larger & better quality images,
* animated gif's, and
* embedded utube and other video's, such as those produced by @bgirardot & others.

My thoughts go along the line of;
many sections of LearnOSM would benefit from better quality images & if some disagree, then at least we will have some feedback. 

The easiest way of doing this would be to submit a pull request with the larger quality image involved / gif / video, and if need be there can be discussion, perhaps involving the HOT Training team.

**Comment by Nick-Tallguy** [comment]
I'm closing this now but acknowledge that this is a long term aim held by me and others. I have made one attempt which we were not happy with and our team will keep working on this when we can.
