### ISSUE TITLE
TM Admin

### ISSUE THREAD

**Issue by tastrax** [hotosm/learnosm#512]
Great work on the task manager training guide. Not a major issue but just a quick note to say the odt and pdf links at the top of the page both fail with a 404.

It might also pay to let folks know how they go about getting Project Manager role added to their login. I assume its via an email to the administrator?

**Comment by michael63-osm** [comment]
.odt and .pdf versions have just been added - thanks for pointing us at this

**Comment by Nick-Tallguy** [comment]
Closing as this was fixed back in December
