### ISSUE TITLE
Links to change colour after they have been selected.

### ISSUE THREAD

**Issue by Nick-Tallguy** [hotosm/learnosm#513]
Request from Sam Colchester;
Sam Colchester [12:14 AM] 
Is there any way to ensure that the links change color once they are selected?

This could help when people are quickly scanning through to know which sections they have already covered

**Comment by michael63-osm** [comment]
I just experimented a bit on the staging site trying to find a hue of green between the dark grey of the "old" links and the light green for the link under the mouse cursor. Feel free to try other values by changing line 158 in style.css, the new specification for a:visited

**Comment by Nick-Tallguy** [comment]
It's probably my eyesight, but I have real problems seeing the pale green that is used for many of the links & headings. In the menu I can't differentiate between what has been visited already and what has not. I've tried changing the colours to something with more of a contrast - far too bright to actually use on the site - I was then able to see the difference.

I think we need someone else to visit the staging site with the colours you have set and they give an opinion. I'll send a message to Sam Colchester asking him to view and we can then go on from there. 

Thanks for working on this @michael63-osm

**Comment by Nick-Tallguy** [comment]
@michael63-osm 
I contacted Sam, and he had similar comments. I've tried a slight variation in the colour - could you take a look and see what you think . I've tried it on Firefox & Chrome on my laptop with a large screen and also on my phone and a tablet. The colour looks slightly different on each, but I can see the difference between visited and not now. 
Feel free to try something different - I've experimented with some quite vivid colours, but came back so something vaguely in the same hue.
Nick

**Comment by michael63-osm** [comment]
Current state is live on the main site for some time now without any objections raised
