### ISSUE TITLE
'Quick Access' link from menu bar

### ISSUE THREAD

**Issue by Nick-Tallguy** [hotosm/learnosm#515]
@michael63-osm 
I think this has been tested quite well - would you like to move it here to the main site and close this issue at the same time?

Keep up the good work!

**Comment by michael63-osm** [comment]
I am not sure yet. In the [last Training WG meeting](https://wiki.openstreetmap.org/wiki/Humanitarian_OSM_Team/Meetings/TrainingWG/2017-01-16#Mapping_tips_for_new_users_in_learnOSM) we said that we might switch the contents to your new mapping tips. So we should first get agreement on this and then move your tips to the main site as well.

**Comment by michael63-osm** [comment]
links are available on the main site
