### ISSUE TITLE
0600-12-08-osmosis.md - possible typo

### ISSUE THREAD

**Issue by Nick-Tallguy** [hotosm/learnosm#518]
Message from translator on transifex that needs investigation;
"Nick whilst translating 0600-12-08-osmosis.md.txt I came across this segment

"- You must add the directory where osm2pgsql.exe is located to the Path variable. "

since the file is about Osmosis I suppose that program is meant, instead of osm2pgsql.exe.

Could (would) you please adjust the source ?

Greetings
Dick"

**Comment by michael63-osm** [comment]
The translator is right - this was probably a copy-paste error. I corrected the English versions on the main and staging sites and updated the source on Transifex
