### ISSUE TITLE
Map design section outdated

### ISSUE THREAD

**Issue by maning** [hotosm/learnosm#520]
Along with [Tilemill](https://github.com/hotosm/learnosm/issues/508), this section should be updated.  A lot of the content is outdated and not supported anymore for example Drupal.  

@rasagy @jinalfoflia @mikelmaron

**Comment by rasagy** [comment]
Specifically, the [Mapbox section](http://learnosm.org/en/map-design/mapbox/) in Map Design is really old — the workflow and pricing have changed.

As an temporary fix, would it help to point to the [Mapbox Studio Manual](http://learnosm.org/en/map-design/mapbox/) that introduces Studio stack as well as has a few tutorials. I know that this will not have translated versions available, but wondering if it makes sense to get started by linking to this section and later drafting a new guide to Mapbox Studio.

Thoughts? 
@Nick-Tallguy @d3netxer (tagging those who I saw active recently, feel free to tag anyone else)

**Comment by Nick-Tallguy** [comment]
Hi,

Thanks for the update.  I'll try to work on it this evening and send a link
to a version for review.

If there's any delay it will be Internet problems on the campsite I'm
currently on.

Please let us know if there are any more out of date bits. Our little team
are not experts on everything and help / advice are welcome.

Once we're happy with a revision I'll put it on the main site and then up
for translation.

Nick (OSM=Tallguy)
my phone is responsible for any spelling mistakes!

**Comment by Nick-Tallguy** [comment]
As my Internet connection is proving unreliable, I've gone ahead and updated both the staging site and the main LearnOSM site while I could. All affected languages should be okay now. At the moment the affected modules have all of the text hidden except for a sentence explaining that the content was out of date and a link to Mapbox with a mention of training materials there.

**Comment by Nick-Tallguy** [comment]
Please also see http://erikakristie.github.io/learnosm/ja/map-design/mapbox/  which I'm seeing in the stats. Japanese visitors are using it.

**Comment by Nick-Tallguy** [comment]
I propose to remove this entire chapter.

For info of Mapbox - Japanese visitors are hitting the remaining 'stub' and there are other versions of the site they are also visiting.

**Comment by Nick-Tallguy** [comment]
Missed Japanese!

**Comment by rasagy** [comment]
@Nick-Tallguy Hey Nick, thanks a lot for removing the outdated section! 🙇
