### ISSUE TITLE
Using LearnOSM material to compile new OSM documentation for OSGeo-Live

### ISSUE THREAD

**Issue by kalxas** [hotosm/learnosm#524]
Hi all,

The OSGeo-Live team (https://live.osgeo.org/) is looking for new documentation for OSM (current OSM overview https://live.osgeo.org/en/overview/osm_overview.html and current quickstart tutorial https://live.osgeo.org/en/quickstart/osm_quickstart.html) and we are wondering if there is any volunteer from your project to help us compile a new quickstart document. 

We think that the following 2 documents could be adapted for our use case:
https://github.com/hotosm/learnosm/blob/gh-pages/_posts/en/1900-12-21-start-josm.md
https://github.com/hotosm/learnosm/blob/gh-pages/_posts/en/0200-12-23-id-editor.md

Best regards,
Angelos
OSGeo-Live PSC chair

**Comment by althio** [comment]
Hi @kalxas 

Glad to see you here and happy that you have interest in the content for OSGeo-Live.

If I understand correctly from other discussions about OSGeo-Live, your deadline is 3 July for this quickstart document, correct?

I would like to help you there :)
Any takers in the LearnOSM team for more English writing/proofreading?

**Comment by kalxas** [comment]
Hi @althio 
Thank you for your response. 
Correct, our deadline for the documentation updates is 3rd of July.
So far the volunteers for this task is you and me, I hope more volunteers can join us soon :)
Any ideas where to reach out asking for more volunteers?

**Comment by Nick-Tallguy** [comment]
I'd like to help on this but don't think I will have time. I'll try to monitor and join in if I can.

**Comment by kalxas** [comment]
Thanks @Nick-Tallguy

**Comment by LibertatisPrius** [comment]
I will probably be able to help but I I've never done anything like this before. I'm primarily familiar with iD but I have some experience with JOSM.

(Just FYI, I learned about this through the Osmf-talk mailing list.)

**Comment by kalxas** [comment]
Thanks @LibertatisPrius 
We will need your help.

**Comment by camerons** [comment]
Hi @kalxas, @althio, @Nick-Tallguy, @LibertatisPrius, @mikelmaron,
Thanks for offering to help.
I'm one of the core members of the OSGeo-Live project, and happy to help mentor people writing documentation for the project.

Our guidelines for writing OSGeo-Live documentation are linked from here:
https://wiki.osgeo.org/wiki/Live_GIS_Disc#Documentation , but to fast track things, our minimum need to get started would be to copy the existing text and images to RST format from: 
* https://github.com/hotosm/learnosm/blob/gh-pages/_posts/en/1900-12-21-start-josm.md and
* https://github.com/hotosm/learnosm/blob/gh-pages/_posts/en/0200-12-23-id-editor.md

Put the text into:
* https://github.com/OSGeo/OSGeoLive-doc/tree/master/en/quickstart/jsom_quickstart.rst and
* https://github.com/OSGeo/OSGeoLive-doc/tree/master/en/quickstart/id_quickstart.rst and

Put images as png into: https://github.com/hotosm/learnosm/blob/gh-pages/_posts/en/1900-12-21-start-josm.md

This would be the minimum needed to get up and running.

If we want to improve quality and consistency, we can then improve the text to align with our writing  standards. The UDig quickstart is our template project we use which contains writing tips:
* https://github.com/OSGeo/OSGeoLive-doc/blob/master/en/quickstart/udig_quickstart.rst

Thanks for offering to help, Cameron

**Comment by camerons** [comment]
With help from @cvvergara, I've taken these ideditor and jsom docs and moved into OSGeo-Live Quickstart docs.
Pull request here: https://github.com/OSGeo/OSGeoLive-doc/pull/254
I've hopefully included the history in the process. 
It should linked in from our cutting edge docs within 24 hours here: http://adhoc.osgeo.osuosl.org/livedvd/docs/en/overview/overview.html
It would be good if someone could review and make sure they look ok. (If you review, please let us know you have so we know it has been checked).
Also, we will be wanting to check these docs are up to date when we release every year. 
@althio, @Nick-Tallguy, @LibertatisPrius, @mikelmaron, I wonder if you'd mind if we asked if you could be a point of contact for this? If so, could you please email me (cameron . shorter AT g m a i l .com with your email address)
Cheers, Cameron

**Comment by althio** [comment]
Hi @camerons 

I proposed https://github.com/OSGeo/OSGeoLive-doc/pull/249 for http://adhoc.osgeo.osuosl.org/livedvd/docs/en/quickstart/osm_quickstart.html

I will try to review OSGeo/OSGeoLive-doc#254 for editors iD and JOSM quickstarts.

**Comment by kalxas** [comment]
Actually I have just merged the pull request to a branch:
https://github.com/OSGeo/OSGeoLive-doc/tree/forvicky
which includes the history of the files.

**Comment by althio** [comment]
Activity is going on this repository: https://github.com/OSGeo/OSGeoLive-doc
Closing here.
