### ISSUE TITLE
Translators - Instructions on how to upload localised images

### ISSUE THREAD

**Issue by Nick-Tallguy** [hotosm/learnosm#526]
I've been contacted by one of the translators who wishes to upload 'localised images' - this has been done before, but there are no instructions that I am aware of. 

See also #329

**Comment by althio** [comment]
Maybe out-of-date: https://github.com/hotosm/learnosm/wiki/Images-guidelines

and found an oldie #94

**Comment by Nick-Tallguy** [comment]
Thanks @althio - there seem to be a few out-of-date guides scattered about. I'm planning to spend some time consolidating them into something sensible. Get it done on the staging site and if everyone is happy then do the same for this main site.   
I have a translator who wants to upload some images, so it's prompted me to start.  

I may well move things, because there seem to be so many links to go through before you actually find something that tells you how to help.  Work in progress......  At the moment I'm about to investigate linking all from <http://nick-tallguy.github.io/en/contribute/> which I think will make it easier. We've also got a 'docs' folder with some guides that just need header matter (I think - will investigate).

Regards

Nick

I'd welcome help & advice. There are several issues on each site that revolve around the same problem.

**Comment by Nick-Tallguy** [comment]
Just as a note - I would like the finished instructions to be uploaded to transifex so they can be translated - would allow translation teams to arrange their own localised images much easier.

**Comment by Nick-Tallguy** [comment]
Closing as this was completed some time ago
