### ISSUE TITLE
updates for iD

### ISSUE THREAD

**Issue by althio** [hotosm/learnosm#534]
- [ ] **right-click editing menu**

- [ ] walkthrough https://github.com/openstreetmap/iD/pull/3921 and its autostart link https://github.com/openstreetmap/iD/issues/4111 [ done: #533 ] [ also in [_posts/en/0200-12-23-id-editor.md](https://github.com/hotosm/learnosm/blob/gh-pages/_posts/en/0200-12-23-id-editor.md) ]

- [ ] keyboard shortcuts 

- [ ] information panels https://github.com/openstreetmap/iD/pull/4121

- [ ] if the section is too long, could be reorganised and split into parts.

**Comment by althio** [comment]
current Table of Contents:

- Beginner’s Guide
  - beginner/id-editor/ The iD Editor
    - Starting the iD Editor
    - iD Editor User Interface
    - Configuring the Background Layer
    - Basic Editing with iD (Adding Points, Drawing Lines, Drawing Shapes (Polygons), Drawing Multipolygons)
    - Saving Your Changes
    - Additional Information and Custom Tags
    - iD versus JOSM

---

Proposal to reorganise and split [rough idea, work in progress]:

- Beginner’s Guide
  - beginner/id-editor/ The iD Editor
    - Starting the iD Editor
    - Basic Editing with iD (Adding Points, Drawing Lines, Drawing Shapes (Polygons))
    - Saving Your Changes
- New guide for iD
  - id-editor/intro 
    - refer to beginner/id-editor/
    - iD versus JOSM
  - id-editor/gui User Interface
    - iD Editor User Interface
    - Configuring the Background Layer
    - Shortcuts
  - id-editor/advanced Advanced
    - Advanced Editing with iD (Drawing Multipolygons, Relations(turn restrictions, route, ...))
    - Information panels (hidden)
    - Additional Information and Custom Tags

**Comment by Nick-Tallguy** [comment]
This is looking pretty good and I'd be delighted if you could do it. Can you do some new screenshots to go with it? My current thinking on images is;  
  - static images for the majority of the site, but  
  - animated gif's for the sections which are likely to be people working using the tasking manager and they can look at the higher bandwidth HOT-Tips section.  

My only concern is the word 'Advanced' - would prefer to see something else as advanced infers you can leave it until later, and I would like even new iD users to be aware of Relations (often used in HOT for boundaries) - don't want them editing boundaries by mistake if possible.

**Comment by Nick-Tallguy** [comment]
Hi,

Closing this now. The iD module within the Beginner section has been completely rewritten by @michael63-osm & I've rewritten the hot-tips modules which covers new mappers using iD and the Tasking Manager. Please reopen if there is something that needs adding.
