### ISSUE TITLE
Osmtracker DOES upload waypoints

### ISSUE THREAD

**Issue by jidanni** [hotosm/learnosm#539]
Please see https://github.com/nguillaumin/osmtracker-android/issues/112 .

**Comment by Nick-Tallguy** [comment]
Hi,

I'm closing this issue - as far as I can see our documentation is correct. 

Although OSM Tracker uploads the complete .gpx file which includes both trackpoints and waypoints, OSM itself does not display or integrate into its database the actual waypoints.

When editing using only the gps traces available on OSM, the labelled waypoints are not visible as they were not accepted into OSM's database. Hence my comment, which I still believe to be correct.
