### ISSUE TITLE
Promote end of the year campaign in banner

### ISSUE THREAD

**Issue by smit1678** [hotosm/learnosm#545]
@michael63-osm @Nick-Tallguy @bgirardot We're trying to get to promote the HOT end of the year campaign by linking to the campaign donation page via a lot of our tools. One idea is to add text and link into the LearnOSM banner. Only needs to be linked until December 31. Thoughts or suggestions on how we could do this better? 

![learnosm 2017-12-19 12-05-36](https://user-images.githubusercontent.com/796838/34171834-79acc73e-e4b5-11e7-8e7a-fe72de9ba6b7.png)

**Comment by althio** [comment]
I don't think learnosm is the good place for a donate banner.

**Comment by michael63-osm** [comment]
In my opinion it is perfectly right to use a banner on websites which are clearly connected to HOT. But learnOSM is a bit different. It is managed by HOT but this is not clearly visible on the website, many visitors will not know that this service was created by HOT. I see the scope of the contents a lot broader than just humanitarian mapping: we try to provide tutorials to people who would like to contribute to or use OSM data. I regularly read questions on the learnosm mail address from people who most likely do not map on HOT projects. Our pages can be found through search engines as well.
 
In view of the recent fierce discussion on some mailing lists about the relationship between HOT and OSM I prefer to let things cool down first before opening what might prove a can of worms.

**Comment by Nick-Tallguy** [comment]
Michael,

I completely agree.

Nick (OSM=Tallguy)
my phone is responsible for any spelling mistakes!

**Comment by smit1678** [comment]
Thanks for the comments @michael63-osm @Nick-Tallguy @althio and considering how and if this could be part of the site.  

> I see the scope of the contents a lot broader than just humanitarian mapping: we try to provide tutorials to people who would like to contribute to or use OSM data.

100% agree @michael63-osm, this is why LearnOSM is such an important resource and valuable as a separate brand. This is also why there is an interest from the Fundraising WG to help promote the end of the year campaign. Since there is a wider reach than just the disaster mapping with LearnOSM for the HOT community, there could be individuals who use LearnOSM as a resource and want to contribute to the campaign for things like the microgrants.

Do we think there could be other ways we could link to the Campaign than just a link in the header that would be more amenable to everyone? 

> In view of the recent fierce discussion on some mailing lists about the relationship between HOT and OSM I prefer to let things cool down first before opening what might prove a can of worms.

I think this is a bit of why I hesitate to add a link in the header too. Do you think this concern is about confusion about who maintains LearnOSM?

**Comment by althio** [comment]
> I see the scope of the contents a lot broader than just humanitarian mapping: we try to provide tutorials to people who would like to contribute to or use OSM data.

👍 my thoughts exactly thanks @michael63-osm 

For other tools, say Task Manager, Slack, ..., you can consider that one instance is HOT-run and other instances do exist and are welcome.
This is not the case with LearnOSM, there is only one LearnOSM and it is intented for the whole OSM community and ecosystem.

Since LearnOSM is for the whole OSM community and ecosystem, I think my concerns are:
- should have a link to donate to OSMF before a link to donate to HOT
- link and text should be permanent features, not short-term campaign focused
- (or do you think you could determine first-time users and returning users, or geo-ip origin? I would not like such a donate campaign to target beginners, first-time visitors or low-income countries)

**Comment by Nick-Tallguy** [comment]
Closing as no longer a current problem
