### ISSUE TITLE
Outdated pdf and odt extracts for Geofabrik and HOT Export

### ISSUE THREAD

**Issue by severinmenard** [hotosm/learnosm#547]
Seems the documents dated from 2016 do not reflect the online chapter: http://learnosm.org/en/osm-data/geofabrik-and-hot-export/

**Comment by michael63-osm** [comment]
Hi Séverin,

thank you for reporting this - I just updated the relevant files which now reflect the current online version. With contents and number of languages growing this will inevitably occur from time to time...

As far as languages are concerned, if you happen to know some French speaking OSM addicts who would like to bring the French version of LearnOSM up-to-date then any help would be greatly appreciated. The current contents was translated before the current workflow with Transifex was implemented and is now a couple of years old. Information on the current process can be found at http://learnosm.org/en/contribute/translator/ and any questions will be answered at learnosm@hotosm.org

Best Regards
Michael
