### ISSUE TITLE
Guide needs rewrite - iD background imagery adjustment

### ISSUE THREAD

**Issue by bgirardot** [hotosm/learnosm#551]
http://nick-tallguy.github.io/en/hot-tips/enhance/

now there are iD built in tools for all of this.

**Comment by Nick-Tallguy** [comment]
see also #302

**Comment by Nick-Tallguy** [comment]
New module has been added - see https://github.com/hotosm/learnosm/commit/412919beb37a31f7170a26b71a5af7c647e1f981.  Closing this issue now. All modules in the hot-tips section have been updated. Please reopen if more work is needed.
