### ISSUE TITLE
Guide needs updating - hot tips, saving and uploading with TM

### ISSUE THREAD

**Issue by bgirardot** [hotosm/learnosm#552]
TM has changed a lot

http://nick-tallguy.github.io/en/hot-tips/saving/

**Comment by Nick-Tallguy** [comment]
See commit https://github.com/hotosm/learnosm/commit/11f4217d3d8b5156c15627bd7d2fc96de3782894 - guide has been updated. Closing this issue, but please reopen if needed. All of the hot-tips modules should now be up to date, and 2 new modules have been added.
