### ISSUE TITLE
Switch to https for jquery, google fonts, license images

### ISSUE THREAD

**Issue by smit1678** [hotosm/learnosm#556]
<img width="1171" alt="learnosm 2018-06-29 10-28-17" src="https://user-images.githubusercontent.com/796838/42085000-28f57eda-7b87-11e8-9768-491892943987.png">

**Comment by Nick-Tallguy** [comment]
Console no longer showing any warnings concerning mixed content

**Comment by smit1678** [comment]
Thanks for doing this @Nick-Tallguy
