### ISSUE TITLE
Print friendly

### ISSUE THREAD

**Issue by vdeparday** [hotosm/learnosm#56]
The PDFs are currently available as Google docs but these will get outdated as pull requests come in. So, it looks like:
- A script should be available in the repo to generate the PDFs (using pandoc?)
- The generated PDFs should have links to them on the website
- Ideally, the PDFs should be generated after each pull request

**Comment by Nick-Tallguy** [comment]
See #319 - the .odt documents was created using pandoc, although I did reformat the .odt to incorporate other sections and tidy up, including a TOC, before producing the .pdf

Feedback welcome please

**Comment by Nick-Tallguy** [comment]
Following on from a move of various topics within the headings, I've produced an .odt & .pdf version of each of the topics now within the beginners guide, in all of the languages, and created links for downloading them. The .odt was produced using pandoc, and only briefly edited (remove some surplus headings for other chapters) before producing the .pdf
My thought is, provide each individually, and the 'trainer' or whoever has the need can amalgamate the .odt document using whichever sections they feel are relevant, and format it as they wish. Adding a TOC and re-sizing the images to suit their needs as they go.

It's not perfect, but I think it is deliverable by me at the moment. 

I'll work on the other sections as the need arises - if you need one, let me know & I'll produce it.

**Comment by d3netxer** [comment]
is there anyway to have the LearnOSM logo appear in the print view? I briefly took a look at this but couldn't figure out how to do this yet. I see the print.css file

**Comment by Nick-Tallguy** [comment]
Hi @d3netxer I've started putting the logo manually into the .odt when I produce or update a document. As you've rightly realised there are a lot that don't have the logo in them. If you fancied adding a few & updating them, that would be great, otherwise they wait for me to get the time to do them.

**Comment by d3netxer** [comment]
I haven't looked at your .odt workflow, but in this thread I'm referring to when someone clicks print in their browser, not the PDFs that are linked to on individual pages.

**Comment by Nick-Tallguy** [comment]
Closing. It would be good if some clever person could automate this. In the meantime I'm using pandoc and manually tidying the result.
