### ISSUE TITLE
page Creating custom presets

### ISSUE THREAD

**Issue by DemonioCZ** [hotosm/learnosm#567]
I found following problems on page:
        learnosm/_posts/en/1900-07-15-creating-custom-presets.md
On learnOSM page:
![learnosm](https://user-images.githubusercontent.com/4252843/53948222-a1478800-40c7-11e9-8f10-0e98f71cc795.png)
on nick-tallguy page:
![nick-tallguy](https://user-images.githubusercontent.com/4252843/53948223-a1478800-40c7-11e9-920a-32318125874e.png)

**Comment by michael63-osm** [comment]
the last commit closes this issue
