### ISSUE TITLE
Text runs off the side

### ISSUE THREAD

**Issue by Nick-Tallguy** [hotosm/learnosm#573]
email from Philip Stein
"Hello, just wanted to make you aware that your text runs off the side of my window, and no control at bottom to move right. I'm losing perhaps 10 characters on right. Window 10 PC.

https://learnosm.org/en/osm-data/getting-data/"

**Comment by Nick-Tallguy** [comment]
![Screenshot from 2019-05-18 23-02-51](https://user-images.githubusercontent.com/6763965/57975442-2224d900-79c1-11e9-8603-a4563250af8b.png)
Checked with my Ubuntu 18.04 laptop, using Firefox web browser - above screenshot shows same problem

**Comment by Nick-Tallguy** [comment]
I've checked through  the site,, also the staging site. Some modules, such as the 'getting data' module have more lines that come close to the right side than other modules. All modules have text which is closer to the right side than it used to be, but for some this is a problem as text becomes missing, off the side.

**Comment by Nick-Tallguy** [comment]
@michael63-osm could you look at this please

**Comment by Nick-Tallguy** [comment]
Style.css has missing space in margin- right line which may be related.

**Comment by Nick-Tallguy** [comment]
working on this now

**Comment by michael63-osm** [comment]
@Nick-Tallguy 
Just to let you know my findings so far (using kind of an inspector built into Opera): style sheet settings are identical for paragraphs with proper and improper formatting but the (calculated) width of the text varies wildly corresponding to what we see. So far I did not learn how that width is calculated

**Comment by Nick-Tallguy** [comment]
@michael63-osm - I've tried altering the line in the css sheet and then running the site locally - did not make any difference. Not sure what is happening here.

**Comment by Nick-Tallguy** [comment]
@michael-63

I've just viewed the weekly ism on my phone and it seems to have a similar
problem. Can you test on desktop.



Nick
my phone is responsible for any spelling mistakes!

**Comment by michael63-osm** [comment]
@Nick-Tallguy 

I hope I just fixed it _on the staging site_. Please have a look before we merge that here. Finally I found a css property for tables which should fix the problem with the width not being inherited.

**Comment by Nick-Tallguy** [comment]
Using my phone staging site looks okay now. Will try to get on my laptop
soon

Nick
my phone is responsible for any spelling mistakes!

**Comment by Nick-Tallguy** [comment]
Hi @michael63-osm 
I've just viewed the staging site on my laptop, and the text no longer overflows. Well done, that seems to have fixed it.

Regards

Nick
