### ISSUE TITLE
Link to Style Guide is outdated

### ISSUE THREAD

**Issue by Andygol** [hotosm/learnosm#591]
https://github.com/hotosm/learnosm/blob/gh-pages/CONTRIBUTING.md#style-guide

Hackpad.com ceased operations after the takeover by Dropbox. It would be nice to update the link with up-to-date information.

**Comment by michael63-osm** [comment]
The whole CONTRIBUTING document is out of date and has not been maintained for years. I removed the link from the README document

I will add some hints about the structure of the documents in the near future. Current information (not only for translators) can be found at https://learnosm.org/en/contribute/translator/
