### ISSUE TITLE
binary format of the chart

### ISSUE THREAD

**Issue by Yuzef** [hotosm/learnosm#609]
Hello Dear developers,

I would like to know in which binary format is the map file information stored.
How can I use charts in my program?

Kind regards

**Comment by michael63-osm** [comment]
The OpenStreetMap servers contain all the data in a database but there are various ways to get exports from this database (you almost certainly want to have a regional export and not the whole world). https://wiki.openstreetmap.org/wiki/Planet.osm explains different options to get them

The OpenStreetMap wiki contains a page (https://wiki.openstreetmap.org/wiki/Using_OpenStreetMap) 
which gives an overview of what can be done with the data including links to ready-made solutions. If you want to do it yourself, that will require either programming skills or familiarity with GIS software, the page I just mentioned contains links for that as well.

**Comment by Yuzef** [comment]
I have already imported Baltic Sea Charts from the OpenSeaMap.org database.
I opened them via OpenCPN 5.0.0 app.

But, the thing is that I want to use charts from OSM_OpenSeaMap in my own application.
I don't know how to do it, beacuse they have special format .KAP

I have quite old application written on VB 6.0. (it's to hard to me to rewrite it to new modern language),
but this app is still great for certain purposes.
So, I want to use your charts instead of my raster old charts in my app. (And also you have much bigger collection of charts)

How can I do it? How can I use them in my project?
I think that may be I can try to use binary format to bypass .KAP format of a file.

Kind regards

**Comment by Yuzef** [comment]
Thank you for your quick response!

I have already imported Baltic Sea Charts from the OpenSeaMap.org database.
I opened them via OpenCPN 5.0.0 app.

But, the thing is that I want to use charts from OSM_OpenSeaMap in my own
application.
I don't know how to do it, beacuse they have special format .KAP

I have quite old application written on VB 6.0. (it's to hard to me to
rewrite it to new modern language),
but this app is still great for certain purposes.
So, I want to use your charts instead of my raster old charts in my app.
(And also you have much bigger collection of charts)

How can I do it? How can I use them in my project?
I think that may be I can try to use binary format to bypass .KAP format of
a file.

Kind regards


Yuzef Zaborovskiy

сб, 11 апр. 2020 г. в 12:08, Michael Heißmeier <notifications@github.com>:

**Comment by michael63-osm** [comment]
Well, this is learnOSM, a project run by the Humanitarian OpenStreetMap team. Although we try to cover various aspects aside from humanitarian mapping too we are definitively no experts on nautical maps and data formats. But looking at OpenSeaMap I see that they provide contact channels: https://www.openseamap.org/index.php?id=kontakt&L=1
I would expect them to know all about how to access the nautical information they show on their website.

**Comment by Yuzef** [comment]
I have already send them the same 1st message as I send to you, but I don't
have response still. I hope they will answer.
Thank you very much for your quick responses one more time.
You are making really cool project!

Kind regards

Yuzef Zaborovskiy

сб, 11 апр. 2020 г. в 21:19, Michael Heißmeier <notifications@github.com>:
