### ISSUE TITLE
Site no longer builds locally - warnings about doc.html

### ISSUE THREAD

**Issue by Nick-Tallguy** [hotosm/learnosm#616]
Very recent change has resulted in the following warning when attempting to run the site locally;  

Build Warning: Layout 'doc' requested in vi/1900-07-15-creating-custom-presets_vi.md does not exist.

This is an extract - the line appears for every file in _posts.  This includes those files that use the rtl documents;

Build Warning: Layout 'doc-rtl' requested in fa/1900-08-15-josm-presets_fa.md does not exist.

**Comment by michael63-osm** [comment]
I just tried both the staging site and the production site (after updating of course) and they build without any warning. The staging site however has a weird navigation menu for the coordination chapter. Obviously now we have the new TM4 documents in all languages but with language and permalink entries for 'en'.

**Comment by Nick-Tallguy** [comment]
Sorry, my mistake - I've just run 'bundle update' for staging and main site and both now build correctly. - closing.
