### ISSUE TITLE
Improvements for RTL 

### ISSUE THREAD

**Issue by iriman** [hotosm/learnosm#618]
Hello! I've made some enhancements for rtl layout and seems it works without problem.

Main changes would be:

- removing dedicated '-rtl' layouts and merging rtl/ltr in same file.
- making a modified copy of `style.css` for handling rtl in a separate `style-rtl.css`.
- adding a new variable `dir: rtl` to front matter (beside `lang:`) of rtl content used for:
  - linking appropriate `style[-rtl].css` in `default` layout and 
  - using appropriate classes in all layouts (`.marginR` / `.marginL` and `.right` / `.left`)

online demo: iriman.github.io

Please see if this follows your requirements, and if so I can prepare a pull request. thanks

_This issue is edited after I found a cleaner way rather than mixing rtl/ltr styles in same css file._

**Comment by michael63-osm** [comment]
Hello @iriman 

suggestions are always welcome, particular for languages and writing systems we are not familiar with. Please make a pull request and we will consider it.

**Comment by michael63-osm** [comment]
This should now be resolved on both the staging and the production site.
