### ISSUE TITLE
Content is cutting off when printing using Firefox

### ISSUE THREAD

**Issue by iriman** [hotosm/learnosm#623]
For example open [this page](https://learnosm.org/en/beginner/id-editor/) and select  print preview from the menu. It looks like this:

![image](https://user-images.githubusercontent.com/8467903/82806985-28834600-9e9c-11ea-8bef-6104e14ba586.png)

Content is cut off at the end of page one. Seems a problem with Firefox. However there's a fix for it. we need to set display mode of `#wrapper` to `block` in the print stylesheet.

**Comment by michael63-osm** [comment]
fixed on both staging and production sites
