### ISSUE TITLE
Quote boxes run out of screen on mobile screen

### ISSUE THREAD

**Issue by iriman** [hotosm/learnosm#625]
Screenshot is from introduction page: https://learnosm.org/en/beginner/introduction/
<img src="https://user-images.githubusercontent.com/8467903/82812996-6dfa4000-9ea9-11ea-890e-7976b82084f6.png" height="50%" width="50%" />

It is caused by this `.doc p`:

https://github.com/hotosm/learnosm/blob/e8cd947019ed8abaa4b771799113741223d02eaf/style.css#L812

**Comment by iriman** [comment]
Actually seems it's because an inconsistency between px and % values. 

here: 

https://github.com/hotosm/learnosm/blob/e8cd947019ed8abaa4b771799113741223d02eaf/style.css#L812

and here:

https://github.com/hotosm/learnosm/blob/e8cd947019ed8abaa4b771799113741223d02eaf/style.css#L236

Do we need `width:95%;`?

**Comment by michael63-osm** [comment]
I just gave it a try on the staging site removing the "width:95%" statement but it does not seem to have any effect on my smartphone.

**Comment by iriman** [comment]
Mine is corrected. Could be an issue with browser cache for you?

![۲۰۲۰۰۶۰۵_۰۵۰۰۴۰](https://user-images.githubusercontent.com/8467903/83823663-bdcad980-a6e9-11ea-95b8-cba243d88e5a.jpg)

**Comment by michael63-osm** [comment]
I assume that you are right - I just merged the fix to the production site

**Comment by iriman** [comment]
Thanks @michael63-osm, it would be great if you could also apply it to the rtl stylesheet. I missed it on the original comment.

**Comment by michael63-osm** [comment]
added to style-rtl.css on both staging and production sites
