### ISSUE TITLE
Display of code examples need improvement

### ISSUE THREAD

**Issue by iriman** [hotosm/learnosm#627]
This is a screenshot from [here](https://learnosm.org/fa/josm/creating-presets/#%D8%A7%DB%8C%D8%AC%D8%A7%D8%AF-%D9%81%D8%A7%DB%8C%D9%84-%D9%82%D8%A7%D9%84%D8%A8-%D8%A2%D9%85%D8%A7%D8%AF%D9%87-%D8%AE%D9%88%D8%AF%D8%AA%D8%A7%D9%86) just before the section:

![image](https://user-images.githubusercontent.com/8467903/83350897-87413780-a354-11ea-9f1c-02e3b1395875.png)

as you see, there are two problems:

- [ ] Content is overflowed
- [ ] This page is RTL, so code block displayed RTL by default. It should become left-to-right, since mostly it's displaying something in English.

What is expecting:

![image](https://user-images.githubusercontent.com/8467903/83350904-945e2680-a354-11ea-8bbb-f609ea19ebee.png)

**Comment by iriman** [comment]
I suggest adding the new rule `white-space: pre-wrap;` to the `pre` element

and a new rule `direction: ltr;` here maybe:
https://github.com/hotosm/learnosm/blob/7b078bcc9d20e89496d7e7734f759a26a422b1e5/style-rtl.css#L724

**Comment by michael63-osm** [comment]
checked locally that it works as expected and added this to staging and production sites
