### ISSUE TITLE
Placeholder of search input box misaligned on mobile screen

### ISSUE THREAD

**Issue by iriman** [hotosm/learnosm#629]
This is how search filed is displayed on my mobile:

<img src="https://user-images.githubusercontent.com/8467903/82814302-20cb9d80-9eac-11ea-9a4a-594030d1bfc2.png" height="50%" width="50%" />

I proposed a fix as a[ pull request](https://github.com/Nick-Tallguy/Nick-Tallguy.github.io/pull/99) on staging site.

**Comment by michael63-osm** [comment]
as it looked promising on the staging site I merged your changes here - thanks for advising us

**Comment by iriman** [comment]
Thank you @michael63-osm, LearnOSM is great and these are a little I know that can make users to feel even better :)
