### ISSUE TITLE
mixed-content

### ISSUE THREAD

**Issue by vdgwebsites** [hotosm/learnosm#631]
https://learnosm.org/en/coordination/HOT-Remote-Response-Guide/

I noticed this page has a mixed-content issue.

![mixed-content-learnosm](https://user-images.githubusercontent.com/17877665/94145972-986a0300-fe73-11ea-83f5-815b266b3310.JPG)

**Comment by michael63-osm** [comment]
Thank you for pointing this out - I just fixed it on both the staging and production sites
