### ISSUE TITLE
Revise section on Downloading OSM data to Garmin

### ISSUE THREAD

**Issue by skorasaurus** [hotosm/learnosm#74]
http://learnosm.org/en/beginner/using-gps/ 

has a note that instructs users to download OSM Data to their garmin to a file that only contains data for Haiti. 

I don't know what approach is most appropriate for this: perhaps link to a page that has all garmin-formatted OSM data for different countries/areas ? Does such a page already exist (on geofabrik) ?  
Unless we want to maintain a page that has all of these exports, just completely remove this portion of text ? 

As of now, the labs has garmin formatted data - http://labs.geofabrik.de/ 
although just for haiti, libya, syria.

**Comment by jmarlena** [comment]
I am not familiar with using GPS devices but I edited the document emirhartato translated. Anyone can edit it: 
https://docs.google.com/document/d/1RKEYfTRsdqT5zyBChIE-tu5ZxS4J9plN-i0WKXJTvcY/edit?usp=sharing

**Comment by Nick-Tallguy** [comment]
I've just reviewed the section on garmin gps which is currently in LearnOSM - must have been updated sometime in the past.
