### ISSUE TITLE
No images for the all chapters section

### ISSUE THREAD

**Issue by maning** [hotosm/learnosm#90]
How to solve this?  If anyone can provide guidelines, I can work on this.

**Comment by pyrog** [comment]
I'am currently working on adding **All chapters** to the french translation (see #303) and I have the same issue.

We must search and replace all? ```{{site.baseurl}}``` from all? files.

**Comment by pyrog** [comment]
This solution work but if we change ```baseurl``` in _config.yml it will fail :wink: 

In **beginner-all-chapters.html** files replace
```jekyll
{{ post.content | markdownify }}
```
by
```jekyll
    {% assign pattern = "{{site.baseurl}}" %}
    {{ post.content | replace: pattern,baseurl | markdownify }}
```

**Note:** we must use 2 lines because the pattern ```{{xxx}}``` don't enter in conflict with liquid pattern ```{%yyyy%}```
