### ISSUE TITLE
Localization of images' content 

### ISSUE THREAD

**Issue by skorasaurus** [hotosm/learnosm#94]
Several pages in other languages have images with text written in English. 

For example, the images for JOSM sections - [JOSM Plugins in French ](http://learnosm.org/fr/beginner/josm-plugins/) 

A quick review of this appears that some of this has been done for the German section - http://learnosm.org/de/beginner/start-josm/

Second related question and probably warrants a separate issue; having a consistent naming scheme for the images which are stored at: https://github.com/hotosm/learnosm/tree/gh-pages/images 
The German images look like they need to be renamed to the scheme used by other languages: 

So, the 2nd image used in chapter 3 of beginning section for Dutch is: 
    nl_beg_ch3_image02.png

This is a pretty big task and probably isn't a priority at the moment (at least not for us in Haiti at the moment). We can use this for discussion and breaking the steps for this. 
- Standardizing image naming schema 
- Taking the screenshots 
- uploading them to here
- making the changes in JOSM.

**Comment by Nick-Tallguy** [comment]
Closing - see #526 and commit on staging site. - working on other issue now
